String[] tMots1A = {
  "obscure", "root", "executable", "header", "the",
  "problem", "with", "universals", "anti-forensics",
  "embedded", "malware", "plastic", "pill", "jars",
  "slamming", "our", "doors", "trapped", "under",
  "the", "rubble", "pile", "the", "boundaries", "as", 
  "my", "own", "emotion", "rocks", "&", "dust", "on", 
  "my", "face", "and", "where", "i", "sleep", "at", 
  "night", "my", "own", "private", "achromatic", 
  "prison", "dark", "alleyways", "and", "elevators", 
  "used", "as", "negotiating", "spaces", "for", 
  "my", "self", "which", "is", "under", "realistic", 
  "scrutiny", "anyway", "personal", "property", 
  "architected", "on", "pleasure", "profit", 
  "principals", "do", "not", "give", "that", "guy",
  "money","obscene", "roosevelt", "executives", "hearsay", "thesis",
  "protista", "wit", "uninterruptedly", "anterior-formative",
  "embellishments", "maloney", "playable", "pillar", "jarvin",
  "slav", "ours", "doolittle", "transact", "undesirable",
  "thereon", "rubles", "pilers", "they", "bourbaki", "as", 
  "my", "owning", "emory", "rocky", "&", "dusk", "on", 
  "my", "factored", "andes", "wheeling", "i", "sleeps", "at", 
  "night", "my", "owner", "priding", "achilles", 
  "primeval", "darkness", "allotter", "andover", "electrocardiograph", 
  "uselessness", "as", "negligence", "sparc", "forums", 
  "my", "selectors", "whitfield", "is", "undecided", "reassemble", 
  "scrolled", "anyplace", "perpendicularly", "promethean", 
  "archers", "on", "pledges", "protected", 
  "privations", "do", "noticing", "givers", "thankful", "guying",
  "monetary","obsession", "roomer", "execute", "hearts", "theoretically",
  "promptest", "withholdings", "uniplus", "antedate-formulators",
  "embed", "malignant", "places", "pilgrim", "jarred",
  "slanted", "our", "doorsteps", "tract", "undeveloped",
  "these", "rubber", "pillar", "thereto", "bouquet", "as", 
  "my", "own", "emotions", "rochford", "&", "dustin", "on", 
  "my", "facsimiles", "andalusian", "whereupon", "i", "sleepers", "at", 
  "nightly", "my", "ownership", "primers", "achievable", 
  "priceless", "darn", "alluring", "andalusian", "elemental", 
  "used", "as", "negotiable", "spate", "forehead", 
  "my", "selves", "whiting", "is", "underdone", "reactions", 
  "scrumptious", "anywhere", "perfects", "protract", 
  "archipelago", "on", "pleasingly", "progresses", 
  "priam", "do", "notably", "giveaway", "thatch", "guyana",
  "montevideo","obscured", "roomer", "exercises", "headline", "thereafter",
  "prolonged", "withholds", "union", "anticipatory-forbearance",
  "embroiders", "maliciously", "playfully", "piling", "jarring",
  "slashed", "ourselves", "doorbell", "transformational", "underestimate",
  "these", "rubbery", "pilots", "theological", "bourgeois", "as", 
  "my", "owner", "emory", "rockies", "&", "dusty", "on", 
  "my", "facades", "andover", "whereby", "i", "sleep", "at", 
  "nightfall", "my", "owns", "prism", "ached", 
  "primarily", "darkroom", "allele", "andrew", "elevation", 
  "usefulness", "as", "negotiation", "spanks", "forklift", 
  "my", "selfsame", "whittles", "is", "underlinings", "reactor", 
  "scrapes", "anybody", "perceive", "protestantize", 
  "arcane", "on", "pleasingly", "profound", 
  "privations", "do", "noticeable", "giving", "thalia", "guyana",
  "monteverd","carbon", "copy", "hear","tz","obscure", "root", "executable", "header", 
"the", "problem", "with", "universals", "anti","forensics", "embedded", 
"malware", "plastic", "pill", "jars", "slamming", "our", "doors", "trapped", 
"under", "the", "rubble", "pile", "the", "boundaries", "as", "my", "own", 
"emotion", "rocks","dust", "on", "my", "face", "and", "where", "i", "sleep", 
"at", "night", "my", "own", "private", "achromatic", "prison", "dark", 
"alleyways", "and", "elevators", "used", "as", "negotiating", "spaces", 
"formy", "self", "which", "is", "under", "realistic", "scrutiny", 
"anywaypersonal", "property", "architected", "on", "pleasure", "profit", 
"principals", "do", "not", "give", "that", "guy", "moneydown", "stream", 
"wastesensing", "a", "quite", "exhaustive", "overhaul", "coming", "on", 
"to", "my", "ideology", "glitter", "swirling", "around", "in", "tanks", 
"takes", "power", "applied", "to", "move", "air", "particles", "that", 
"collide", "with", "small", "colorful", "bits", "of", "new", "reality", 
"that", "represent", "practice", "and", "stars", "and", "stripe", "that", 
"start", "again", "charging", "charging", "charging", "charging", "for", 
"their", "productivity", "charging", "for", "their", "scandal", "not", 
"enough", "violence", "is", "what", "i","m", "toldi", "turned", "my", 
"hairdryer", "to", "it","s", "highest", "setting", "napping", "in", 
"the", "bathroom", "turn", "the", "grill", "to", "it","s", "highest", 
"setting", "mark", "ourselves", "again", "and", "again", "with", "the", 
"hot", "knife", "until", "we", "remember", "our", "heroines", "we", 
"can", "show", "it", "off", "without", "misunderstanding", "remember", 
"what", "it", "felt", "like", "to", "do", "nothing", "and", "be", 
"fine", "about", "nothing", "challenge", "the", "pleasure", 
"principal", "cash", "out", "my", "purest", "pursuit", "expectations", 
"explode", "lose", "your", "soul", "for", "your", "country", "yell", 
"all", "along", "the", "way", "home", "from", "school", "reveal", 
"structured", "sub","grids", "that", "carried", "power", "along", 
"lines", "too", "thin", "and", "strung", "about", "haphazardly", 
"after", "the", "sky", "replaced", "the", "order", "of", "the", 
"telephone", "poles", "the", "becoming", "and", "going", "of", 
"structured", "sub","grids", "that", "carried", "power", "along", 
"lines", "too", "thin", "and", "strung", "about", "haphazardly", 
"because", "of", "the", "storm", "all", "terrain", "is", "dodgy", 
"in", "that", "there", "is", "a", "more", "efficient", "way", "of", 
"lighting", "these", "bombs", "off", "well", "he", "shot", "some", 
"stuff", "up", "to", "the", "moon", "there","s", "a", "formal", 
"way", "to", "fuck", "it", "all", "just", "do", "it", "and", "apply", 
"rigorously", "daily", "at", "regular", "intervals", "until", 
"swelling", "abbess", "rescinds", "into", "the", "depths", "of", 
"direct", "quotation", "having", "nothing", "at", "all", "to", "do", 
"with", "context", "but", "yet", "somehow", "linked", "but", "U",
"shaped", "lines", "over", "matte", "the", "image", "of", "your", 
"memory", "the", "formal", "way", "to", "fuck", "it", "all","apply", 
"rigorously", "daily", "at", "regular", "intervals", "until", 
"swelling", "abbess", "rescinds", "into", "depths", "of", "direct", 
"quotation", "having", "nothing", "at", "all", "to", "do", "with", 
"context", "but", "yet", "somehow", "linked", "but", "U","shaped", 
"lines", "over", "matte", "the", "image", "of", "memory", "having", 
"nothing", "at", "all", "to", "do", "with", "context", "but", "yet", 
"somehow", "linked", "like", "K","shaped", "lines", "over", "the", 
"matte", "image", "of", "memory", "recumbent", "growth", "is", "to", 
"be", "excepted", "and", "anticipation", "is", "anguish", "even", 
"though", "the", "winters", "are", "worse", "they", "say", "it","s", 
"both", "coming", "soon","salvation","destruction", "recumbent", 
"growth", "is", "to", "be", "excepted", "and", "anticipation", "is", 
"anguish", "even", "though", "the", "winters", "are", "worse","coming", 
"soon","salvation","destruction", "turbulent", "youth", "diaries", "are", 
"like", "clouds", "they", "were", "talking", "to", "each", "other", 
"but", "mouths", "werenot", "moving", "it","s", "handheld","carelessly", "copiers", "heaped","t","observation", "roomers", "exempts", "heal", "they", "protectorate", "wits", "uniformly", "anticoagulation","forestry", "embellished", "malone", "platteville", "pillory", "jars", "slaver", "ourself", "doorman", "traverses", "underplays", "therefore", "ruby", "pilferage", "theoretically", "bouncy", "as", "my", "owned", "emory", "rocked","dustbin", "on", "my", "faceted", "andalusia", "wheatstone", "i", "slewing", "at", "nigerian", "my", "owners", "printers", "achieve", "primal", "darker", "allusiveness", "and", "elements", "used", "as", "negotiates", "spaniards", "formulationmy", "seller", "whitespace", "is", "undergone", "reassembling", "scripture", "anythingperfumed", "proportionally", "archfool", "on", "plebiscite", "protocol", "privilege", "do", "notifications", "giver", "thank", "guyers", "monetdowel", "strong", "washessensibly", "a", "quickening", "exhume", "overshot", "comical", "on", "to", "my", "identify", "glimmer", "swingers", "arousal", "in", "tantalizing", "takers", "powerlessness", "approvers", "to", "movers", "airers", "parody", "thanksgiving", "coliform", "withstanding", "smart", "collection", "bitternut", "of", "newspapers", "realism", "thailand", "reprehensible", "prague", "anders", "stabled", "andalusians", "stressing", "thanklessness", "staging", "agates", "chasteness", "chameleon", "challenging", "charting", "forestry", "thessalonian", "prostitution", "chairmen", "fortuitously", "thesis", "scalloped", "noteworthy", "enormous", "violating", "is", "whaling", "i","m", "toleratei", "turret", "my", "hairier", "to", "it","s", "higher", "settlers", "naps", "in", "theorists", "battlegrounds", "turtles", "theological", "grilled", "to", "it","s", "higher", "seth", "marking", "our", "agate", "andy", "agape", "withers", "theatricals", "hotels", "knit", "untouchable", "we", "remunerate", "our", "heroes", "we", "canned", "shoot", "it", "offensive", "witt", "miscellaneous", "reminds", "whales", "it", "felice", "likely", "to", "do", "nothing", "anderson", "be", "fining", "aborts", "notice", "chattahoochee", "theirs", "plebiscite", "printably", "castroism", "outskirts", "my", "puritanic", "purposive", "explosion", "exponentiate", "losing", "youthfully", "southampton", "forested", "youth", "courtyard", "yeller", "allocations", "aloha", "thereby", "wayward", "homesick", "frowned", "schooner", "revels", "strayed", "subvert","gripped", "thawed", "caramel", "powerlessly", "aloha", "linguistically", "toothpick", "thinkable", "andrews", "strip", "abominate", "happening", "afterward", "theoretic", "skylights", "republicans", "thermofax", "ordinariness", "of", "therapists", "telephoned", "polyphemus", "theme", "becalmed", "andalusians", "goings", "of", "straits", "sublimation","grip", "thatch", "carlo", "powerlessly", "aloof", "lind", "toothbrush", "thin", "andrew", "strindberg", "abominable", "haplessly", "becomes", "of", "theft", "stoning", "alleviate", "terrorize", "is", "dodging", "in", "thankful", "theorize", "is", "a", "morbidly", "effeminate", "wayne", "of", "lightest", "therapeutic", "bombed", "offsetting", "welch", "he", "shockingly", "somberly", "stupendous", "up", "to", "theoretic", "moon", "therapeutic","s", "a", "forums", "waynesboro", "to", "fuchsia", "it", "alliterations", "justinian", "do", "it", "and", "appointing", "rig", "daisy", "at", "regime", "introspection", "untenable", "sweeping", "abbreviated", "residual", "interrelate", "thermodynamic", "depleted", "of", "directors", "quotes", "havana", "notifications", "at", "alleviation", "to", "do", "withdrawn", "consuls", "butterflies", "yet", "someplace", "lindstrom", "butterers", "U","shaving", "lined", "overrides", "matchings", "thesis", "imaginative", "of", "youthes", "memorable", "thermometers", "forte", "waynesboro", "to", "fuchsia", "it", "allegiance","appended", "rigging", "daimler", "at", "regimentation", "interrelate", "unthinking", "sweetly", "abbots", "resembled", "intentness", "deposition", "of", "dirtier", "quoth", "having", "notable", "at", "alleges", "to", "do", "withdrawals", "convergent", "butterflies", "yet", "sometime", "lint", "buttonhole", "U","sharecroppers", "linkers", "overshoot", "matriarchal", "themselves", "imaginations", "of", "memories", "havoc", "notices", "at", "allotter", "to", "do", "with", "confirmatory", "buttrick", "yet", "sommerfeld", "linden", "liken", "K","shambles", "liners", "overdraft", "theoreticians", "material", "imaging", "of", "memoryless", "rectangle", "groups", "is", "to", "be", "excelling", "andy", "anti", "is", "angry", "evenhandedly", "thoroughfare", "thermosphere", "winding", "arena", "worth", "thermosphere", "sayers", "it","s", "botched", "comradeship", "soothing","salve","desuetude", "recreate", "grotesquely", "is", "to", "be", "exclusiveness", "andre", "antimicrobial", "is", "anguish", "eveready", "thoughtfully", "therefore", "win", "arenas", "wordiness","commentaries", "soon","salerno","deserting", "turns", "youthes", "diagnoses", "ares", "likeliest", "clot", "their", "werther", "talent", "to", "each", "otherwise", "buttons", "mount", "werner", "moving", "it","s", "handful",
 "carbonated", "copra", "headline","t","obsession", "roofed", "exemplifier", "headed", "theorizing", "promoters", "wittgenstein", "unions", "antarctic","formatively", "embrace", "malignantly", "placing", "pilots", "jarred", "slanted", "ours", "doorways", "transit", "underneath", "thebes", "rube", "pillars", "thereof", "boundless", "as", "my", "owning", "emotions", "rock","dustbin", "on", "my", "factor", "andalusia", "wheatstone", "i", "sleeps", "at", "nightingale", "my", "owned", "prides", "ached", "primaries", "darted", "allusion", "andy", "elegantly", "uselessly", "as", "negotiation", "spat", "forevermy", "sellout", "whirling", "is", "understandably", "realtor", "scraper", "anywhereperfectionist", "prognosticate", "arching", "on", "plea", "prostate", "prima", "do", "notations", "given", "thatches", "guyers", "montdownside", "stringed", "wastesenators", "a", "quit", "exhortations", "oversee", "comprised", "on", "to", "my", "identifiable", "glitter", "swiftly", "aroused", "in", "tangibly", "takings", "powering", "applaud", "to", "move", "airy", "parachute", "thankful", "colors", "withdrawing", "smarter", "columbus", "biting", "of", "newman", "reactionary", "thaw", "reprover", "prayer", "andromeda", "stallings", "anders", "stroker", "thatches", "state", "agape", "chairman", "chaucer", "chatter", "chartres", "forbids", "therapists", "probating", "chaffing", "forcefulness", "theatrical", "scanned", "noticing", "enormities", "violet", "is", "whatsoever", "i","m", "tolerabilityi", "turpentine", "my", "hairier", "to", "it","s", "highway", "setup", "napoleon", "in", "themes", "bathers", "turmoil", "thelma", "grist", "to", "it","s", "highways", "settings", "marc", "ours", "against", "andrews", "agape", "witching", "thermodynamic", "hotness", "knife", "untouchables", "we", "remission", "ourself", "herein", "we", "cannot", "shook", "it", "offsetting", "wit", "misunderstander", "removable", "whaler", "it", "feline", "likenesses", "to", "do", "nothing", "andrew", "be", "finnegan", "abolishers", "notifying", "chargeable", "theorizes", "pleat", "privacies", "cassites", "outstretched", "my", "purely", "pursuer", "expending", "experimentation", "los", "youngest", "soul", "forefathers", "youthes", "couched", "yelps", "allophone", "aloft", "then", "waynesboro", "homesick", "frozenly", "scheming", "revealing", "strap", "sub","grievingly", "thanklessness", "carr", "powder", "aloe", "linguistic", "tools", "thirdly", "andalusians", "street", "aboriginal", "haplessly", "afterwards", "theseus", "skylight", "repudiate", "thereupon", "ordains", "of", "then", "televised", "police", "theodosius", "become", "andalusians", "goings", "of", "stragglers", "subtitled","gripe", "thankful", "caracas", "powering", "aloud", "linux", "tools", "thieves", "anding", "stroking", "abodes", "haphazardly", "becoming", "of", "thelma", "stolen", "alleges", "terror", "is", "dodger", "in", "thankfulness", "thermal", "is", "a", "moran", "effectors", "wayside", "of", "lighthouse", "theatricals", "bombers", "officialdom", "wellesley", "he", "show", "someplace", "studebaker", "up", "to", "thessaly", "moonlight", "thermometers","s", "a", "fortifying", "ways", "to", "fuchsia", "it", "allocations", "justify", "do", "it", "anders", "appetites", "rights", "daintiness", "at", "regulars", "interleaves", "untold", "swellings", "abbott", "result", "integrated", "theoretical", "deprivations", "of", "dirts", "quotas", "having", "notorious", "at", "allowably", "to", "do", "withhold", "confusing", "buttery", "yet", "somalis", "lingo", "butchers", "U","shatters", "linguist", "overgrown", "maturation", "therewith", "imaginable", "of", "youngest", "memory", "thermofax", "foreman", "wayside", "to", "fuchsia", "it", "allotropic","appointers", "rigs", "daimler", "at", "regular", "intangible", "untruthful", "sweeper", "abbe", "restaurants", "interrogation", "dependencies", "of", "direction", "quotient", "havoc", "notwithstanding", "at", "allegoric", "to", "do", "withholder", "confuse", "buttrick", "yet", "somnolent", "linearizable", "butterfat", "U","shallowly", "lint", "overpower", "matured", "therefore", "imagen", "of", "memorize", "havoc", "notches", "at", "alleging", "to", "do", "withdrawal", "conceptions", "butted", "yet", "someday", "linnaeus", "likenesses", "K","shaped", "lindsay", "overloads", "thefts", "material", "imaginative", "of", "memos", "reclaimers", "groped", "is", "to", "be", "excitedly", "andromeda", "anteater", "is", "angeleno", "evened", "thornburg", "the", "winged", "ares", "workman", "theorem", "sayer", "it","s", "botany", "comparably", "soon","salish","designation", "reciprocating", "group", "is", "to", "be", "exclude", "andrea", "anthropologically", "is", "angle", "everest", "thornburg", "thereabouts", "winking", "areas", "worshipful","comedy", "soothed","salk","desired", "turn", "youthfulness", "diamonds", "ares", "likeliness", "closing", "theory", "were", "talented", "to", "each", "otherwise", "but", "mournfully", "werner", "move", "it","s", "hangar", 
 "carmela", "copes", "heart","t","obscene", "roommate", "exerciser", "hearts", "thermostats", "propelled", "withhold", "unidirectional", "anticipates","forger", "embodies", "malaysian", "platinum", "pillow", "jarring", "slashed", "ourself", "dooms", "tragedy", "underplayed", "thermometer", "rubber", "pillared", "theatrically", "bough", "as", "my", "owners", "emotion", "rocky","dusts", "on", "my", "faction", "andrei", "whelp", "i", "sledge", "at", "nightcap", "my", "own", "prizes", "ache", "prided", "darpa", "allah", "andersen", "elegance", "user", "as", "negotiating", "spank", "forestallmy", "selfishly", "whistling", "is", "undecidable", "realized", "screwball", "anymoreperemptory", "procedure", "architects", "on", "pleat", "protective", "prizes", "do", "notations", "giving", "thankless", "guyed", "monetarismdowns", "stratagems", "washoesends", "a", "quiescent", "exhales", "overhangs", "commentator", "on", "to", "my", "identifiers", "glints", "swift", "arouses", "in", "tanners", "take", "powder", "appealer", "to", "moves", "aires", "pardoners", "thailand", "collector", "witty", "smaller", "coldly", "bitches", "of", "newness", "reason", "thankful", "repletion", "pragmatism", "andy", "statesmanlike", "andalusia", "stranglers", "thayer", "stalins", "against", "charities", "chargeable", "chauffeur", "chantilly", "fortitude", "thea", "proficiency", "channeller", "fort", "theorem", "scatter", "notching", "enormous", "violins", "is", "whales", "i","m", "toleratesi", "turned", "my", "hailstorm", "to", "it","s", "highest", "settlers", "napoleonic", "in", "theresa", "bathes", "turkish", "thematic", "grindstone", "to", "it","s", "higher", "seth", "march", "ourself", "agar", "andersen", "agates", "withholding", "thesis", "hotly", "knightly", "untenable", "we", "remission", "ours", "hermetically", "we", "cancel", "shoveled", "it", "officialdom", "within", "mischief", "remorse", "wharf", "it", "felony", "likewise", "to", "do", "noted", "and", "be", "financing", "abolishment", "not", "charon", "thermodynamics", "plead", "privileges", "casuals", "outstandingly", "my", "purportedly", "purging", "expeditiously", "explanatory", "lose", "you", "sources", "formant", "younger", "counterman", "yellowish", "allegorical", "aloud", "thereupon", "wayside", "homogeneously", "frostbelt", "schelling", "reversely", "structures", "subtleness","grieve", "thalia", "caravan", "powders", "aloha", "lindstrom", "toothbrushes", "thinker", "andorra", "strengthened", "abolished", "happened", "aftermost", "thessaly", "skylark", "repartition", "thermometers", "order", "of", "theodosian", "telephone", "polishes", "them", "bechtel", "and", "going", "of", "stratifies", "subsist","grievance", "thank", "carlyle", "powering", "alongside", "lining", "toothbrushes", "thistle", "andalusia", "strengthening", "abolishes", "happiness", "becoming", "of", "theme", "stowed", "allows", "terraces", "is", "dodgers", "in", "thanking", "theorist", "is", "a", "mortifying", "effectually", "ways", "of", "lighthouse", "therewith", "bombardment", "officially", "welcomes", "he", "shortish", "sometime", "stung", "up", "to", "theorization", "moored", "theory","s", "a", "foretell", "wayward", "to", "fuchsia", "it", "allied", "justifies", "do", "it", "anders", "approvers", "righted", "daisies", "at", "reginald", "intrastate", "unto", "swelter", "abbey", "resemble", "intercommunication", "then", "depicted", "of", "directories", "quotas", "havens", "notwithstanding", "at", "alleged", "to", "do", "withholding", "congressional", "buttes", "yet", "someone", "linen", "butts", "U","shamefully", "lineup", "overprint", "maturely", "thermodynamics", "image", "of", "youngest", "memphis", "theological", "forestry", "ways", "to", "fuchsia", "it", "alloys","apprising", "righteous", "daisy", "at", "regrets", "introduced", "untold", "sweeneys", "abbreviation", "resolvers", "intimations", "deposits", "of", "dirtiness", "quoting", "havana", "notifications", "at", "alludes", "to", "do", "within", "contemplative", "buttering", "yet", "sommerfeld", "lindstrom", "buttressing", "U","shapes", "linking", "overproduction", "mate", "thereto", "imaginably", "of", "memories", "haves", "notation", "at", "allow", "to", "do", "wither", "context", "button", "yet", "someone", "linearizes", "liken", "K","shampoo", "lincoln", "overly", "these", "materializing", "imaginatively", "of", "memorially", "recant", "grooves", "is", "to", "be", "excommunicates", "andersen", "anticipated", "is", "angled", "evenly", "thought", "therefore", "wintered", "arequipa", "workbench", "theorizes", "say", "it","s", "bothered", "comfortability", "soothes","sales","destitution", "recover", "grover", "is", "to", "be", "excessive", "andy", "antiformant", "is", "anguished", "events", "thousands", "theodosian", "winnipesaukee", "area", "worthlessness","compaction", "sooner","salted","destuffing", "turmoil", "younger", "diagnosing", "area", "likewise", "closed", "theoretical", "werther", "talmudism", "to", "each", "others", "buttresses", "mounts", "werner", "movements", "it","s", "handwriting",
 "locomotor",
"movement",
"that",
"travels",
"from",
"one",
"space",
"to",
"another",
"space",
"1. walk",
"2. run",
"3. jog",
"4. scamper",
"5. stroll",
"6. meander",
"7. tiptoe",
"8. skip",
"9. prance",
"10. leap",
"11. jump",
"12. roll",
"13. snake",
"14. creep",
"15. crawl",
"16. wriggle",
"17. grow",
"18. dash",
"19. drive",
"20. move",
"21. zigzag",
"22. slide",
"23. waltz",
"24. hop",
"25. climb",
"26. gallop",
"27. tumble",
"28. skate",
"29. march",
"30. stomp",
"31. scoot",
"32. shuffle",
"33. waddle",
"34. trip",
"35. flip",
"36. moonwalk",
"37. slither",
"38. cat-walk",
"39. bear-walk ",
"40. dinosaur walk",
"locker",
"move",
"thankfully",
"transponders",
"frozen",
"oneida",
"sparseness",
"to",
"anointed",
"sparc",
"0. walkers",
"5. runs",
"9. jogging",
"4. scarecrow",
"8. strauss",
"2. meander",
"7. tipper",
"9. skillet",
"2. prayer",
"71. leaders",
"29. jumped",
"58. rollback",
"59. snappily",
"43. creepy",
"96. craze",
"25. writes",
"01. groans",
"22. dashing",
"71. drifter",
"78. moving",
"73. ziggy",
"44. sling",
"52. wallowing",
"01. hopkinsian",
"75. climatically",
"87. galloped",
"97. tumbled",
"20. skate",
"92. marvelling",
"84. stoppable",
"28. scorings",
"26. shutting",
"59. wades",
"54. trier",
"49. flipped",
"48. moore",
"89. slits",
"22. catherwood-waldensian",
"66. beatings-waltzing ",
"54. dinnerware walcott",
"from",
"slowest",
"to",
"quickest",
"1. Crawl",
"2. Plod",
"3. Trudge",
"4. Tiptoe",
"5. Creep",
"6. Edge",
"7. Worm",
"8. Stagger",
"9. Waddle",
"10. Traipse",
"11. Amble",
"12. Dawdle",
"13. Mosey",
"14. Saunter",
"15. Promenade",
"16. Slink",
"17. Maunder",
"18. Perambulate",
"19. Stroll",
"20. Walk",
"21. Scuttle",
"22. Strut",
"23. Sashay",
"24. Gad",
"25. Prance",
"26. Roll",
"27. Skip",
"28. Flounce",
"29. Stomp",
"30. Scoot",
"31. Scramble",
"32. Lope",
"33. Hie",
"34. Bound",
"35. Run",
"36. Hurry",
"37. Scamper",
"38. Spring",
"39. Rush",
"40. Gambol",
"41. Skitter",
"42. Dart",
"43. Race",
"44. Sprint",
"45. Streak",
"46. Gallop",
"47. Dash",
"48. Bolt",
"49. Barrel",
"50. Zoom",
"51. Zip",
"performance",
"ideaz",
"two",
"three",
"stand",
"on",
"one",
"side",
"of",
"a",
"protruded",
"plank",
"another",
"moves",
"on",
"the",
"other",
"end",
"a",
"plank",
"x",
"placed",
"on",
"a",
"school",
"desk",
"the",
"PPL",
"school",
"desk",
"with",
"x",
"performers",
"placed",
"on",
"either",
"side",
"one",
"performer",
"edward",
"is",
"casting",
"arm",
"hand",
"lipstick",
"apply",
"to",
"plank",
"apply",
"to",
"another",
"person",
"then",
"they",
"apply",
"to",
"plank",
"kiss",
"plank",
"down",
"center",
"someone",
"cuts",
"the",
"entire",
"length",
"of",
"board",
"vas",
"aline",
"the",
"bottoms",
"of",
"yr",
"feet",
"try",
"to",
"dance",
"on",
"tarp",
"or",
"walk",
"down",
"plank",
"apply",
"lipstick",
"cutline",
"to",
"x",
"have",
"other",
"people",
"sit",
"on",
"one",
"stable",
"end",
"i",
"sit",
"on",
"the",
"other",
"and",
"cut",
"myself",
"off",
"repeat",
"x",
"ketchup",
"redpaint",
"in",
"mouth",
"write",
"word",
"on",
"wall",
"floor",
"spank",
"my",
"ass",
"pick",
"people",
"up",
"while",
"they",
"read",
"thingz",
"off",
"phone",
"or",
"receipt",
"paper",
"apply",
"paint",
"to",
"heelz",
"and",
"have",
"someone",
"drag",
"me",
"around",
"high",
"heelz",
"black",
"out",
"feet",
"with",
"magic",
"marker",
"black",
"trash",
"bags",
"latex",
"glovez",
"balloonz",
"filled",
"with",
"something",
"poetry",
"language",
"space",
"board",
"brick",
"stand",
"write",
"on",
"x",
"butler",
"nothing",
"lay",
"and",
"receive",
"projectionz",
"on",
"body",
"zizek",
"meaning",
"eater",
"blind",
"with",
"bags",
"over",
"our",
"heads",
"one",
"person",
"will",
"use",
"language",
"to",
"explain",
"their",
"movement",
"and",
"other",
"will",
"try",
"to",
"emulate",
"movement",
"tie",
"everyones",
"head",
"together",
"take",
"clothes",
"off",
"and",
"describe",
"them",
"x",
"mouthpiece",
"saw",
"x",
"into",
"mouth",
"shape",
"on",
"both",
"ends",
"x",
"x",
"people",
"carry",
"around",
"rd",
"person",
"reading",
"receipt",
"txt",
"have",
"someone",
"else",
"put",
"my",
"bootz",
"on",
"I",
"lick",
"them",
"p",
"jelly",
"feet",
"bag",
"head",
"have",
"some",
"yank",
"sheet",
"tarp",
"out",
"from",
"under",
"me",
"Carry",
"board",
"from",
"storage",
"shed", "persuading",
"ideal",
"twombly",
"threatens",
"staircases",
"on",
"onerous",
"side",
"of",
"a",
"propellers",
"placer",
"anon",
"moving",
"on",
"themselves",
"otherwise",
"endings",
"a",
"platonist",
"x",
"placed",
"on",
"a",
"schroeder",
"desmond",
"therapist",
"BMF",
"schaefer",
"destructions",
"witherspoon",
"x",
"perceptibly",
"playboy",
"on",
"either",
"sidestep",
"oneself",
"perfect",
"edwardine",
"is",
"cassites",
"armada",
"handful",
"lips",
"appoints",
"to",
"planoconvex",
"apprise",
"to",
"anomalous",
"peruse",
"theorist",
"theorization",
"appreciating",
"to",
"placement",
"kisses",
"platitude",
"downstairs",
"centigrade",
"someplace",
"cuttings",
"then",
"entropy",
"leniency",
"of",
"boa",
"vastness",
"alienating",
"theodosian",
"bottlers",
"of",
"yr",
"feelingly",
"try",
"to",
"dandelion",
"on",
"tardy",
"or",
"walnuts",
"downed",
"placidly",
"apprehension",
"lipton",
"cutters",
"to",
"x",
"havilland",
"others",
"peoples",
"sits",
"on",
"onerous",
"staley",
"endows",
"i",
"situation",
"on",
"theorizations",
"others",
"andes",
"cutthroat",
"mysteriousness",
"offhand",
"repents",
"x",
"ketchup",
"reducibility",
"in",
"mouton",
"wristwatches",
"workbook",
"on",
"walk",
"florin",
"spanking",
"my",
"assigners",
"picasso",
"peoria",
"up",
"whiteleaf",
"theodosian",
"realizably",
"thinner",
"officialdom",
"phone",
"or",
"recapitulated",
"papered",
"approved",
"paine",
"to",
"heeds",
"andes",
"having",
"somerville",
"drained",
"me",
"arousal",
"highest",
"heeds",
"blanks",
"outstripped",
"feelers",
"withholders",
"magnitude",
"marshal",
"blackout",
"trains",
"bagatelle",
"latinity",
"globally",
"balking",
"filaments",
"withholder",
"somnolent",
"poe",
"landmarks",
"spareness",
"boarding",
"brittany",
"starkly",
"writhe",
"on",
"x",
"buttercup",
"notables",
"laymen",
"andre",
"reclamations",
"probes",
"on",
"bodybuilding",
"xixec",
"meander",
"eats",
"blip",
"wit",
"bagel",
"overthrown",
"ours",
"headmaster",
"onerous",
"perpetrate",
"wily",
"used",
"lancer",
"to",
"expressive",
"thefts",
"moving",
"andalusian",
"others",
"wiley",
"trying",
"to",
"emulates",
"moves",
"tientsin",
"everlasting",
"heart",
"togo",
"takers",
"clone",
"officio",
"andrea",
"destined",
"thereof",
"x",
"mourner",
"sawmill",
"x",
"interlaces",
"mouse",
"shallowness",
"on",
"botany",
"endeared",
"x",
"x",
"peopled",
"carbonization",
"aromatic",
"rd",
"perspective",
"reacted",
"reconfigurations",
"vkb",
"have",
"some",
"elsie",
"putnam",
"my",
"bookcase",
"on",
"I",
"licentious",
"thereof",
"p",
"jelly",
"feels",
"bagging",
"heaved",
"haven",
"somali",
"yank",
"shea",
"tar",
"outdo",
"frostbite",
"underestimates",
"me",
"Carriers",
"boasted",
"frontal",
"stony",
"sheet", 
"perfection",
"identifications",
"twos",
"thrill",
"stare",
"on",
"oneida",
"sidesaddle",
"of",
"a",
"proud",
"placer",
"anomaly",
"movements",
"on",
"theology",
"otherworldly",
"endanger",
"a",
"planoconcave",
"x",
"plateaus",
"on",
"a",
"schematically",
"designator",
"theorist",
"VQY",
"schedulable",
"despise",
"withdrawals",
"x",
"percy",
"placards",
"on",
"either",
"sideboard",
"oneness",
"percy",
"edwards",
"is",
"cassius",
"armpits",
"hannibal",
"lipschitz",
"apprentices",
"to",
"plaguing",
"appearances",
"to",
"anonymous",
"perseid",
"theology",
"theirs",
"appian",
"to",
"playwright",
"kisser",
"plant",
"downtown",
"centrifugal",
"somatic",
"cutting",
"their",
"enters",
"lentil",
"of",
"boatloads",
"vassar",
"aliasing",
"thereafter",
"bothering",
"of",
"yr",
"feeder",
"trying",
"to",
"dangle",
"on",
"tardiness",
"or",
"waltham",
"downtowns",
"planes",
"appreciations",
"lipschitz",
"cutaneous",
"to",
"x",
"havana",
"othello",
"peopled",
"sit",
"on",
"oneida",
"stager",
"endeavored",
"i",
"sited",
"on",
"theology",
"otherwise",
"andrews",
"cute",
"mystic",
"officemate",
"replies",
"x",
"kettles",
"redden",
"in",
"mounts",
"wriggler",
"worthiness",
"on",
"walford",
"floored",
"spareness",
"my",
"assembly",
"picofarad",
"peopled",
"up",
"whiteleaf",
"theorizers",
"realists",
"thinner",
"officer",
"phosphor",
"or",
"receipt",
"paperweight",
"apportionment",
"pairings",
"to",
"heeded",
"andre",
"havoc",
"something",
"dragon",
"me",
"arousing",
"highfield",
"heeded",
"blanket",
"outermost",
"feel",
"witt",
"magnet",
"marketplace",
"blanchard",
"transferred",
"bagels",
"latter",
"gloom",
"ballpark",
"file",
"witchcraft",
"somatic",
"poetically",
"landscaping",
"sparest",
"boasted",
"bribers",
"stabilizer",
"writhed",
"on",
"x",
"butterers",
"notwithstanding",
"layering",
"andrei",
"recover",
"proliferating",
"on",
"bodice",
"xomiy",
"measuring",
"eat",
"blink",
"withdrew",
"bagley",
"oversight",
"ours",
"headland",
"onerous",
"persuasiveness",
"willingness",
"usenet",
"landings",
"to",
"experts",
"theatricals",
"moves",
"andorra",
"otherwise",
"willow",
"trying",
"to",
"emulator",
"moved",
"tiers",
"evenhanded",
"healthier",
"together",
"take",
"closets",
"offshore",
"anders",
"deserter",
"therewith",
"x",
"moulton",
"sawmill",
"x",
"interfacing",
"mourn",
"shall",
"on",
"botanical",
"endeavors",
"x",
"x",
"peony",
"carmela",
"aromatic",
"rd",
"persecuting",
"reacquired",
"reconsider",
"gfj",
"havilland",
"sommerfeld",
"elsevier",
"putter",
"my",
"boom",
"on",
"I",
"licensor",
"theatrical",
"p",
"jello",
"feeder",
"bagged",
"headphone",
"having",
"somali",
"yankee",
"sheds",
"tartuffe",
"outgrew",
"front",
"undergoing",
"me",
"Carrying",
"boarsh",
"frowned",
"stomacher",
"shell",
"of",
"a",
"situation",
"or",
"condition",
"extremely",
"bad",
"unpleasant",
"and",
"degrading",
"abject",
"poverty",
"synonyms",
"wretched",
"miserable",
"hopeless",
"pathetic",
"pitiful",
"pitiable",
"piteous",
"sorry",
"woeful",
"lamentable",
"degrading",
"appalling",
"atrocious",
"awful",
"abject",
"poverty",
"of",
"an",
"unhappy",
"state",
"of",
"mind",
"experienced",
"to",
"the",
"maximum",
"degree",
"his",
"letter",
"plunged",
"her",
"into",
"abject",
"misery",
"of",
"a",
"person",
"or",
"their",
"behavior",
"completely",
"without",
"pride",
"or",
"dignity",
"self",
"abasing",
"an",
"abject",
"apology",
"synonyms",
"contemptible",
"base",
"low",
"vile",
"worthless",
"debased",
"degraded",
"despicable",
"ignominious",
"mean",
"unworthy",
"ignoble",
"an",
"abject",
"sinner",
"obsequious",
"groveling",
"fawning",
"toadyish",
"servile",
"cringing",
"sycophantic",
"submissive",
"craven",
"an",
"abject",
"apology",
"of",
"a",
"sitting",
"or",
"constituencies",
"extremal",
"badge",
"unpaid",
"andalusia",
"degenerated",
"abjured",
"poverty",
"synergy",
"wretched",
"misting",
"hopper",
"patterning",
"pityingly",
"pithiness",
"pities",
"sordidly",
"woefully",
"lame",
"degree",
"appellation",
"atrophying",
"awful",
"abject",
"poverty",
"of",
"an",
"unhappy",
"stalk",
"of",
"minsk",
"exposition",
"to",
"thelma",
"maximally",
"degenerated",
"histogram",
"letitia",
"plunderer",
"herein",
"intentions",
"abject",
"mishaps",
"of",
"a",
"perpetuated",
"or",
"theory",
"beholds",
"complementary",
"withholders",
"privately",
"or",
"digitizing",
"selwyn",
"abandoning",
"an",
"abjures",
"apostate",
"syndrome",
"contradistinction",
"baseboards",
"lowliest",
"vilified",
"workload",
"debby",
"degenerative",
"deserter",
"ignores",
"measured",
"unwinding",
"ignominious",
"an",
"abjections",
"singapore",
"observance",
"groups",
"fawn",
"toasted",
"serializations",
"crimean",
"sycophant",
"subsisting",
"crater",
"an",
"abjections",
"apologists",
"centimeter",
"long",
"lengths",
"of",
"copper",
"wire",
"copper",
"space",
"islands",
"copper",
"wires",
"to",
"wrap",
"the",
"world",
"the",
"pre",
"dated",
"makeshift",
"decisions",
"a",
"big",
"house",
"banging",
"on",
"a",
"drum",
"for",
"survival",
"for",
"fitness",
"for",
"dexterity",
"cooperatively",
"bang",
"together",
"and",
"own",
"the",
"house",
"ya",
"banging",
"and",
"ya",
"cooperation",
"ya",
"dexterity",
"and",
"ya",
"cooperation",
"glitchy",
"little",
"innards",
"makeshift",
"lantern",
"makeshift",
"candle",
"made",
"out",
"of",
"my",
"duplicated",
"head",
"carved",
"out",
"the",
"temple",
"of",
"the",
"dupe",
"filled",
"the",
"hole",
"in",
"the",
"dupe",
"with",
"beeswax",
"dollar",
"bill",
"wic",
"women",
"infants",
"children",
"put",
"on",
"the",
"government",
"s",
"grave",
"doing",
"what",
"s",
"safe",
"and",
"removing",
"clothes",
"probably",
"a",
"thief",
"probably",
"a",
"victim",
"probably",
"too",
"resentful",
"probably",
"too",
"stressful",
"failure",
"and",
"success",
"are",
"not",
"spectrums",
"saturated",
"stress",
"but",
"you",
"ain",
"t",
"gotta",
"worry",
"about",
"me",
"ya",
"got",
"yr",
"own",
"yeah",
"the",
"coveted",
"formation",
"of",
"crystals",
"in",
"dark",
"caves",
"cause",
"suffering",
"why",
"my",
"opportunity",
"is",
"displaced",
"oppression",
"why",
"guess",
"imma",
"keep",
"drinking",
"this",
"water"
}; 
String[] tMots1B = {
  "obscene", "roosevelt", "executives", "hearsay", "thesis",
  "protista", "wit", "uninterruptedly", "anterior-formative",
  "embellishments", "maloney", "playable", "pillar", "jarvin",
  "slav", "ours", "doolittle", "transact", "undesirable",
  "thereon", "rubles", "pilers", "they", "bourbaki", "as", 
  "my", "owning", "emory", "rocky", "&", "dusk", "on", 
  "my", "factored", "andes", "wheeling", "i", "sleeps", "at", 
  "night", "my", "owner", "priding", "achilles", 
  "primeval", "darkness", "allotter", "andover", "electrocardiograph", 
  "uselessness", "as", "negligence", "sparc", "forums", 
  "my", "selectors", "whitfield", "is", "undecided", "reassemble", 
  "scrolled", "anyplace", "perpendicularly", "promethean", 
  "archers", "on", "pledges", "protected", 
  "privations", "do", "noticing", "givers", "thankful", "guying",
  "monetary"
};

String[] tMots1C = {
  "obsession", "roomer", "execute", "hearts", "theoretically",
  "promptest", "withholdings", "uniplus", "antedate-formulators",
  "embed", "malignant", "places", "pilgrim", "jarred",
  "slanted", "our", "doorsteps", "tract", "undeveloped",
  "these", "rubber", "pillar", "thereto", "bouquet", "as", 
  "my", "own", "emotions", "rochford", "&", "dustin", "on", 
  "my", "facsimiles", "andalusian", "whereupon", "i", "sleepers", "at", 
  "nightly", "my", "ownership", "primers", "achievable", 
  "priceless", "darn", "alluring", "andalusian", "elemental", 
  "used", "as", "negotiable", "spate", "forehead", 
  "my", "selves", "whiting", "is", "underdone", "reactions", 
  "scrumptious", "anywhere", "perfects", "protract", 
  "archipelago", "on", "pleasingly", "progresses", 
  "priam", "do", "notably", "giveaway", "thatch", "guyana",
  "montevideo"
};

String[] tMots1D = {
  "obscured", "roomer", "exercises", "headline", "thereafter",
  "prolonged", "withholds", "union", "anticipatory-forbearance",
  "embroiders", "maliciously", "playfully", "piling", "jarring",
  "slashed", "ourselves", "doorbell", "transformational", "underestimate",
  "these", "rubbery", "pilots", "theological", "bourgeois", "as", 
  "my", "owner", "emory", "rockies", "&", "dusty", "on", 
  "my", "facades", "andover", "whereby", "i", "sleep", "at", 
  "nightfall", "my", "owns", "prism", "ached", 
  "primarily", "darkroom", "allele", "andrew", "elevation", 
  "usefulness", "as", "negotiation", "spanks", "forklift", 
  "my", "selfsame", "whittles", "is", "underlinings", "reactor", 
  "scrapes", "anybody", "perceive", "protestantize", 
  "arcane", "on", "pleasingly", "profound", 
  "privations", "do", "noticeable", "giving", "thalia", "guyana",
  "monteverdi"
};


String[] tMots2A = {
"carbon", "copy", "hear","tz","obscure", "root", "executable", "header", 
"the", "problem", "with", "universals", "anti","forensics", "embedded", 
"malware", "plastic", "pill", "jars", "slamming", "our", "doors", "trapped", 
"under", "the", "rubble", "pile", "the", "boundaries", "as", "my", "own", 
"emotion", "rocks","dust", "on", "my", "face", "and", "where", "i", "sleep", 
"at", "night", "my", "own", "private", "achromatic", "prison", "dark", 
"alleyways", "and", "elevators", "used", "as", "negotiating", "spaces", 
"formy", "self", "which", "is", "under", "realistic", "scrutiny", 
"anywaypersonal", "property", "architected", "on", "pleasure", "profit", 
"principals", "do", "not", "give", "that", "guy", "moneydown", "stream", 
"wastesensing", "a", "quite", "exhaustive", "overhaul", "coming", "on", 
"to", "my", "ideology", "glitter", "swirling", "around", "in", "tanks", 
"takes", "power", "applied", "to", "move", "air", "particles", "that", 
"collide", "with", "small", "colorful", "bits", "of", "new", "reality", 
"that", "represent", "practice", "and", "stars", "and", "stripe", "that", 
"start", "again", "charging", "charging", "charging", "charging", "for", 
"their", "productivity", "charging", "for", "their", "scandal", "not", 
"enough", "violence", "is", "what", "i","m", "toldi", "turned", "my", 
"hairdryer", "to", "it","s", "highest", "setting", "napping", "in", 
"the", "bathroom", "turn", "the", "grill", "to", "it","s", "highest", 
"setting", "mark", "ourselves", "again", "and", "again", "with", "the", 
"hot", "knife", "until", "we", "remember", "our", "heroines", "we", 
"can", "show", "it", "off", "without", "misunderstanding", "remember", 
"what", "it", "felt", "like", "to", "do", "nothing", "and", "be", 
"fine", "about", "nothing", "challenge", "the", "pleasure", 
"principal", "cash", "out", "my", "purest", "pursuit", "expectations", 
"explode", "lose", "your", "soul", "for", "your", "country", "yell", 
"all", "along", "the", "way", "home", "from", "school", "reveal", 
"structured", "sub","grids", "that", "carried", "power", "along", 
"lines", "too", "thin", "and", "strung", "about", "haphazardly", 
"after", "the", "sky", "replaced", "the", "order", "of", "the", 
"telephone", "poles", "the", "becoming", "and", "going", "of", 
"structured", "sub","grids", "that", "carried", "power", "along", 
"lines", "too", "thin", "and", "strung", "about", "haphazardly", 
"because", "of", "the", "storm", "all", "terrain", "is", "dodgy", 
"in", "that", "there", "is", "a", "more", "efficient", "way", "of", 
"lighting", "these", "bombs", "off", "well", "he", "shot", "some", 
"stuff", "up", "to", "the", "moon", "there","s", "a", "formal", 
"way", "to", "fuck", "it", "all", "just", "do", "it", "and", "apply", 
"rigorously", "daily", "at", "regular", "intervals", "until", 
"swelling", "abbess", "rescinds", "into", "the", "depths", "of", 
"direct", "quotation", "having", "nothing", "at", "all", "to", "do", 
"with", "context", "but", "yet", "somehow", "linked", "but", "U",
"shaped", "lines", "over", "matte", "the", "image", "of", "your", 
"memory", "the", "formal", "way", "to", "fuck", "it", "all","apply", 
"rigorously", "daily", "at", "regular", "intervals", "until", 
"swelling", "abbess", "rescinds", "into", "depths", "of", "direct", 
"quotation", "having", "nothing", "at", "all", "to", "do", "with", 
"context", "but", "yet", "somehow", "linked", "but", "U","shaped", 
"lines", "over", "matte", "the", "image", "of", "memory", "having", 
"nothing", "at", "all", "to", "do", "with", "context", "but", "yet", 
"somehow", "linked", "like", "K","shaped", "lines", "over", "the", 
"matte", "image", "of", "memory", "recumbent", "growth", "is", "to", 
"be", "excepted", "and", "anticipation", "is", "anguish", "even", 
"though", "the", "winters", "are", "worse", "they", "say", "it","s", 
"both", "coming", "soon","salvation","destruction", "recumbent", 
"growth", "is", "to", "be", "excepted", "and", "anticipation", "is", 
"anguish", "even", "though", "the", "winters", "are", "worse","coming", 
"soon","salvation","destruction", "turbulent", "youth", "diaries", "are", 
"like", "clouds", "they", "were", "talking", "to", "each", "other", 
"but", "mouths", "werenot", "moving", "it","s", "handheld"
}; 

String[] tMots2B = {
"carelessly", "copiers", "heaped","t","observation", "roomers", "exempts", "heal", "they", "protectorate", "wits", "uniformly", "anticoagulation","forestry", "embellished", "malone", "platteville", "pillory", "jars", "slaver", "ourself", "doorman", "traverses", "underplays", "therefore", "ruby", "pilferage", "theoretically", "bouncy", "as", "my", "owned", "emory", "rocked","dustbin", "on", "my", "faceted", "andalusia", "wheatstone", "i", "slewing", "at", "nigerian", "my", "owners", "printers", "achieve", "primal", "darker", "allusiveness", "and", "elements", "used", "as", "negotiates", "spaniards", "formulationmy", "seller", "whitespace", "is", "undergone", "reassembling", "scripture", "anythingperfumed", "proportionally", "archfool", "on", "plebiscite", "protocol", "privilege", "do", "notifications", "giver", "thank", "guyers", "monetdowel", "strong", "washessensibly", "a", "quickening", "exhume", "overshot", "comical", "on", "to", "my", "identify", "glimmer", "swingers", "arousal", "in", "tantalizing", "takers", "powerlessness", "approvers", "to", "movers", "airers", "parody", "thanksgiving", "coliform", "withstanding", "smart", "collection", "bitternut", "of", "newspapers", "realism", "thailand", "reprehensible", "prague", "anders", "stabled", "andalusians", "stressing", "thanklessness", "staging", "agates", "chasteness", "chameleon", "challenging", "charting", "forestry", "thessalonian", "prostitution", "chairmen", "fortuitously", "thesis", "scalloped", "noteworthy", "enormous", "violating", "is", "whaling", "i","m", "toleratei", "turret", "my", "hairier", "to", "it","s", "higher", "settlers", "naps", "in", "theorists", "battlegrounds", "turtles", "theological", "grilled", "to", "it","s", "higher", "seth", "marking", "our", "agate", "andy", "agape", "withers", "theatricals", "hotels", "knit", "untouchable", "we", "remunerate", "our", "heroes", "we", "canned", "shoot", "it", "offensive", "witt", "miscellaneous", "reminds", "whales", "it", "felice", "likely", "to", "do", "nothing", "anderson", "be", "fining", "aborts", "notice", "chattahoochee", "theirs", "plebiscite", "printably", "castroism", "outskirts", "my", "puritanic", "purposive", "explosion", "exponentiate", "losing", "youthfully", "southampton", "forested", "youth", "courtyard", "yeller", "allocations", "aloha", "thereby", "wayward", "homesick", "frowned", "schooner", "revels", "strayed", "subvert","gripped", "thawed", "caramel", "powerlessly", "aloha", "linguistically", "toothpick", "thinkable", "andrews", "strip", "abominate", "happening", "afterward", "theoretic", "skylights", "republicans", "thermofax", "ordinariness", "of", "therapists", "telephoned", "polyphemus", "theme", "becalmed", "andalusians", "goings", "of", "straits", "sublimation","grip", "thatch", "carlo", "powerlessly", "aloof", "lind", "toothbrush", "thin", "andrew", "strindberg", "abominable", "haplessly", "becomes", "of", "theft", "stoning", "alleviate", "terrorize", "is", "dodging", "in", "thankful", "theorize", "is", "a", "morbidly", "effeminate", "wayne", "of", "lightest", "therapeutic", "bombed", "offsetting", "welch", "he", "shockingly", "somberly", "stupendous", "up", "to", "theoretic", "moon", "therapeutic","s", "a", "forums", "waynesboro", "to", "fuchsia", "it", "alliterations", "justinian", "do", "it", "and", "appointing", "rig", "daisy", "at", "regime", "introspection", "untenable", "sweeping", "abbreviated", "residual", "interrelate", "thermodynamic", "depleted", "of", "directors", "quotes", "havana", "notifications", "at", "alleviation", "to", "do", "withdrawn", "consuls", "butterflies", "yet", "someplace", "lindstrom", "butterers", "U","shaving", "lined", "overrides", "matchings", "thesis", "imaginative", "of", "youthes", "memorable", "thermometers", "forte", "waynesboro", "to", "fuchsia", "it", "allegiance","appended", "rigging", "daimler", "at", "regimentation", "interrelate", "unthinking", "sweetly", "abbots", "resembled", "intentness", "deposition", "of", "dirtier", "quoth", "having", "notable", "at", "alleges", "to", "do", "withdrawals", "convergent", "butterflies", "yet", "sometime", "lint", "buttonhole", "U","sharecroppers", "linkers", "overshoot", "matriarchal", "themselves", "imaginations", "of", "memories", "havoc", "notices", "at", "allotter", "to", "do", "with", "confirmatory", "buttrick", "yet", "sommerfeld", "linden", "liken", "K","shambles", "liners", "overdraft", "theoreticians", "material", "imaging", "of", "memoryless", "rectangle", "groups", "is", "to", "be", "excelling", "andy", "anti", "is", "angry", "evenhandedly", "thoroughfare", "thermosphere", "winding", "arena", "worth", "thermosphere", "sayers", "it","s", "botched", "comradeship", "soothing","salve","desuetude", "recreate", "grotesquely", "is", "to", "be", "exclusiveness", "andre", "antimicrobial", "is", "anguish", "eveready", "thoughtfully", "therefore", "win", "arenas", "wordiness","commentaries", "soon","salerno","deserting", "turns", "youthes", "diagnoses", "ares", "likeliest", "clot", "their", "werther", "talent", "to", "each", "otherwise", "buttons", "mount", "werner", "moving", "it","s", "handful"
}; 

String[] tMots2C = {
"carbonated", "copra", "headline","t","obsession", "roofed", "exemplifier", "headed", "theorizing", "promoters", "wittgenstein", "unions", "antarctic","formatively", "embrace", "malignantly", "placing", "pilots", "jarred", "slanted", "ours", "doorways", "transit", "underneath", "thebes", "rube", "pillars", "thereof", "boundless", "as", "my", "owning", "emotions", "rock","dustbin", "on", "my", "factor", "andalusia", "wheatstone", "i", "sleeps", "at", "nightingale", "my", "owned", "prides", "ached", "primaries", "darted", "allusion", "andy", "elegantly", "uselessly", "as", "negotiation", "spat", "forevermy", "sellout", "whirling", "is", "understandably", "realtor", "scraper", "anywhereperfectionist", "prognosticate", "arching", "on", "plea", "prostate", "prima", "do", "notations", "given", "thatches", "guyers", "montdownside", "stringed", "wastesenators", "a", "quit", "exhortations", "oversee", "comprised", "on", "to", "my", "identifiable", "glitter", "swiftly", "aroused", "in", "tangibly", "takings", "powering", "applaud", "to", "move", "airy", "parachute", "thankful", "colors", "withdrawing", "smarter", "columbus", "biting", "of", "newman", "reactionary", "thaw", "reprover", "prayer", "andromeda", "stallings", "anders", "stroker", "thatches", "state", "agape", "chairman", "chaucer", "chatter", "chartres", "forbids", "therapists", "probating", "chaffing", "forcefulness", "theatrical", "scanned", "noticing", "enormities", "violet", "is", "whatsoever", "i","m", "tolerabilityi", "turpentine", "my", "hairier", "to", "it","s", "highway", "setup", "napoleon", "in", "themes", "bathers", "turmoil", "thelma", "grist", "to", "it","s", "highways", "settings", "marc", "ours", "against", "andrews", "agape", "witching", "thermodynamic", "hotness", "knife", "untouchables", "we", "remission", "ourself", "herein", "we", "cannot", "shook", "it", "offsetting", "wit", "misunderstander", "removable", "whaler", "it", "feline", "likenesses", "to", "do", "nothing", "andrew", "be", "finnegan", "abolishers", "notifying", "chargeable", "theorizes", "pleat", "privacies", "cassites", "outstretched", "my", "purely", "pursuer", "expending", "experimentation", "los", "youngest", "soul", "forefathers", "youthes", "couched", "yelps", "allophone", "aloft", "then", "waynesboro", "homesick", "frozenly", "scheming", "revealing", "strap", "sub","grievingly", "thanklessness", "carr", "powder", "aloe", "linguistic", "tools", "thirdly", "andalusians", "street", "aboriginal", "haplessly", "afterwards", "theseus", "skylight", "repudiate", "thereupon", "ordains", "of", "then", "televised", "police", "theodosius", "become", "andalusians", "goings", "of", "stragglers", "subtitled","gripe", "thankful", "caracas", "powering", "aloud", "linux", "tools", "thieves", "anding", "stroking", "abodes", "haphazardly", "becoming", "of", "thelma", "stolen", "alleges", "terror", "is", "dodger", "in", "thankfulness", "thermal", "is", "a", "moran", "effectors", "wayside", "of", "lighthouse", "theatricals", "bombers", "officialdom", "wellesley", "he", "show", "someplace", "studebaker", "up", "to", "thessaly", "moonlight", "thermometers","s", "a", "fortifying", "ways", "to", "fuchsia", "it", "allocations", "justify", "do", "it", "anders", "appetites", "rights", "daintiness", "at", "regulars", "interleaves", "untold", "swellings", "abbott", "result", "integrated", "theoretical", "deprivations", "of", "dirts", "quotas", "having", "notorious", "at", "allowably", "to", "do", "withhold", "confusing", "buttery", "yet", "somalis", "lingo", "butchers", "U","shatters", "linguist", "overgrown", "maturation", "therewith", "imaginable", "of", "youngest", "memory", "thermofax", "foreman", "wayside", "to", "fuchsia", "it", "allotropic","appointers", "rigs", "daimler", "at", "regular", "intangible", "untruthful", "sweeper", "abbe", "restaurants", "interrogation", "dependencies", "of", "direction", "quotient", "havoc", "notwithstanding", "at", "allegoric", "to", "do", "withholder", "confuse", "buttrick", "yet", "somnolent", "linearizable", "butterfat", "U","shallowly", "lint", "overpower", "matured", "therefore", "imagen", "of", "memorize", "havoc", "notches", "at", "alleging", "to", "do", "withdrawal", "conceptions", "butted", "yet", "someday", "linnaeus", "likenesses", "K","shaped", "lindsay", "overloads", "thefts", "material", "imaginative", "of", "memos", "reclaimers", "groped", "is", "to", "be", "excitedly", "andromeda", "anteater", "is", "angeleno", "evened", "thornburg", "the", "winged", "ares", "workman", "theorem", "sayer", "it","s", "botany", "comparably", "soon","salish","designation", "reciprocating", "group", "is", "to", "be", "exclude", "andrea", "anthropologically", "is", "angle", "everest", "thornburg", "thereabouts", "winking", "areas", "worshipful","comedy", "soothed","salk","desired", "turn", "youthfulness", "diamonds", "ares", "likeliness", "closing", "theory", "were", "talented", "to", "each", "otherwise", "but", "mournfully", "werner", "move", "it","s", "hangar"
}; 

String[] tMots2D = {
"carmela", "copes", "heart","t","obscene", "roommate", "exerciser", "hearts", "thermostats", "propelled", "withhold", "unidirectional", "anticipates","forger", "embodies", "malaysian", "platinum", "pillow", "jarring", "slashed", "ourself", "dooms", "tragedy", "underplayed", "thermometer", "rubber", "pillared", "theatrically", "bough", "as", "my", "owners", "emotion", "rocky","dusts", "on", "my", "faction", "andrei", "whelp", "i", "sledge", "at", "nightcap", "my", "own", "prizes", "ache", "prided", "darpa", "allah", "andersen", "elegance", "user", "as", "negotiating", "spank", "forestallmy", "selfishly", "whistling", "is", "undecidable", "realized", "screwball", "anymoreperemptory", "procedure", "architects", "on", "pleat", "protective", "prizes", "do", "notations", "giving", "thankless", "guyed", "monetarismdowns", "stratagems", "washoesends", "a", "quiescent", "exhales", "overhangs", "commentator", "on", "to", "my", "identifiers", "glints", "swift", "arouses", "in", "tanners", "take", "powder", "appealer", "to", "moves", "aires", "pardoners", "thailand", "collector", "witty", "smaller", "coldly", "bitches", "of", "newness", "reason", "thankful", "repletion", "pragmatism", "andy", "statesmanlike", "andalusia", "stranglers", "thayer", "stalins", "against", "charities", "chargeable", "chauffeur", "chantilly", "fortitude", "thea", "proficiency", "channeller", "fort", "theorem", "scatter", "notching", "enormous", "violins", "is", "whales", "i","m", "toleratesi", "turned", "my", "hailstorm", "to", "it","s", "highest", "settlers", "napoleonic", "in", "theresa", "bathes", "turkish", "thematic", "grindstone", "to", "it","s", "higher", "seth", "march", "ourself", "agar", "andersen", "agates", "withholding", "thesis", "hotly", "knightly", "untenable", "we", "remission", "ours", "hermetically", "we", "cancel", "shoveled", "it", "officialdom", "within", "mischief", "remorse", "wharf", "it", "felony", "likewise", "to", "do", "noted", "and", "be", "financing", "abolishment", "not", "charon", "thermodynamics", "plead", "privileges", "casuals", "outstandingly", "my", "purportedly", "purging", "expeditiously", "explanatory", "lose", "you", "sources", "formant", "younger", "counterman", "yellowish", "allegorical", "aloud", "thereupon", "wayside", "homogeneously", "frostbelt", "schelling", "reversely", "structures", "subtleness","grieve", "thalia", "caravan", "powders", "aloha", "lindstrom", "toothbrushes", "thinker", "andorra", "strengthened", "abolished", "happened", "aftermost", "thessaly", "skylark", "repartition", "thermometers", "order", "of", "theodosian", "telephone", "polishes", "them", "bechtel", "and", "going", "of", "stratifies", "subsist","grievance", "thank", "carlyle", "powering", "alongside", "lining", "toothbrushes", "thistle", "andalusia", "strengthening", "abolishes", "happiness", "becoming", "of", "theme", "stowed", "allows", "terraces", "is", "dodgers", "in", "thanking", "theorist", "is", "a", "mortifying", "effectually", "ways", "of", "lighthouse", "therewith", "bombardment", "officially", "welcomes", "he", "shortish", "sometime", "stung", "up", "to", "theorization", "moored", "theory","s", "a", "foretell", "wayward", "to", "fuchsia", "it", "allied", "justifies", "do", "it", "anders", "approvers", "righted", "daisies", "at", "reginald", "intrastate", "unto", "swelter", "abbey", "resemble", "intercommunication", "then", "depicted", "of", "directories", "quotas", "havens", "notwithstanding", "at", "alleged", "to", "do", "withholding", "congressional", "buttes", "yet", "someone", "linen", "butts", "U","shamefully", "lineup", "overprint", "maturely", "thermodynamics", "image", "of", "youngest", "memphis", "theological", "forestry", "ways", "to", "fuchsia", "it", "alloys","apprising", "righteous", "daisy", "at", "regrets", "introduced", "untold", "sweeneys", "abbreviation", "resolvers", "intimations", "deposits", "of", "dirtiness", "quoting", "havana", "notifications", "at", "alludes", "to", "do", "within", "contemplative", "buttering", "yet", "sommerfeld", "lindstrom", "buttressing", "U","shapes", "linking", "overproduction", "mate", "thereto", "imaginably", "of", "memories", "haves", "notation", "at", "allow", "to", "do", "wither", "context", "button", "yet", "someone", "linearizes", "liken", "K","shampoo", "lincoln", "overly", "these", "materializing", "imaginatively", "of", "memorially", "recant", "grooves", "is", "to", "be", "excommunicates", "andersen", "anticipated", "is", "angled", "evenly", "thought", "therefore", "wintered", "arequipa", "workbench", "theorizes", "say", "it","s", "bothered", "comfortability", "soothes","sales","destitution", "recover", "grover", "is", "to", "be", "excessive", "andy", "antiformant", "is", "anguished", "events", "thousands", "theodosian", "winnipesaukee", "area", "worthlessness","compaction", "sooner","salted","destuffing", "turmoil", "younger", "diagnosing", "area", "likewise", "closed", "theoretical", "werther", "talmudism", "to", "each", "others", "buttresses", "mounts", "werner", "movements", "it","s", "handwriting"
}; 

String[] tMots3A = {
"locomotor",
"movement",
"that",
"travels",
"from",
"one",
"space",
"to",
"another",
"space",
"1. walk",
"2. run",
"3. jog",
"4. scamper",
"5. stroll",
"6. meander",
"7. tiptoe",
"8. skip",
"9. prance",
"10. leap",
"11. jump",
"12. roll",
"13. snake",
"14. creep",
"15. crawl",
"16. wriggle",
"17. grow",
"18. dash",
"19. drive",
"20. move",
"21. zigzag",
"22. slide",
"23. waltz",
"24. hop",
"25. climb",
"26. gallop",
"27. tumble",
"28. skate",
"29. march",
"30. stomp",
"31. scoot",
"32. shuffle",
"33. waddle",
"34. trip",
"35. flip",
"36. moonwalk",
"37. slither",
"38. cat-walk",
"39. bear-walk ",
"40. dinosaur walk"
}; 

String[] tMots3B = {
"locker",
"move",
"thankfully",
"transponders",
"frozen",
"oneida",
"sparseness",
"to",
"anointed",
"sparc",
"0. walkers",
"5. runs",
"9. jogging",
"4. scarecrow",
"8. strauss",
"2. meander",
"7. tipper",
"9. skillet",
"2. prayer",
"71. leaders",
"29. jumped",
"58. rollback",
"59. snappily",
"43. creepy",
"96. craze",
"25. writes",
"01. groans",
"22. dashing",
"71. drifter",
"78. moving",
"73. ziggy",
"44. sling",
"52. wallowing",
"01. hopkinsian",
"75. climatically",
"87. galloped",
"97. tumbled",
"20. skate",
"92. marvelling",
"84. stoppable",
"28. scorings",
"26. shutting",
"59. wades",
"54. trier",
"49. flipped",
"48. moore",
"89. slits",
"22. catherwood-waldensian",
"66. beatings-waltzing ",
"54. dinnerware walcott"
}; 

String[] tMots3C = {
"location",
"movies",
"than",
"tramps",
"frowning",
"oneness",
"spank",
"to",
"anomaly",
"spared",
"6. walford",
"3. rung",
"3. jogging",
"8. scatterbrain",
"5. stripping",
"2. meaty",
"2. tip",
"6. skills",
"0. praisingly",
"26. leagued",
"91. jumble",
"74. rollers",
"72. snare",
"15. creamery",
"91. craving",
"08. writhed",
"47. groveling",
"38. dashboard",
"99. drinkers",
"78. movies",
"85. zigzag",
"56. slippery",
"44. wales",
"32. hopelessly",
"45. clique",
"02. galatia",
"69. tumult",
"61. skates",
"21. marcus",
"56. stop",
"18. scoundrels",
"76. shuttle",
"61. wadsworth",
"86. tried",
"59. flitting",
"58. moody",
"53. slighter",
"37. catalina-walruses",
"79. bearer-walk ",
"26. din waltham"
}; 

String[] tMots3D = {
"localities",
"movement",
"thanksgivings",
"transformations",
"frozenly",
"one",
"sparsely",
"to",
"anomaly",
"spacesuit",
"1. walters",
"6. runyon",
"2. jogs",
"2. scarecrow",
"4. straggled",
"7. meaningfully",
"8. tips",
"9. skins",
"6. prayed",
"92. leap",
"91. jumpy",
"46. roll",
"16. snarling",
"69. creon",
"01. crafty",
"31. writs",
"04. groundwork",
"17. dashers",
"41. drifts",
"59. movies",
"15. ziggy",
"49. slice",
"04. waltham",
"37. hopefulness",
"88. climate",
"37. galbreath",
"70. tumult",
"79. skate",
"21. marx",
"00. stoichiometry",
"36. scorns",
"73. shun",
"70. wader",
"21. triers",
"33. flirting",
"87. moonshine",
"41. slippage",
"21. categorized-waldensian",
"90. beadle-walt ",
"21. dinah walruses"
}; 

String[] tMots4A = {
"non-locomotor",
"movement",
"on",
"the",
"spot",
"without",
"going",
"anywhere",
"1. wave",
"2. rub",
"3. sink",
"4. rise",
"5. melt",
"6. bend",
"7. glide ",
"8. twist",
"9. swing",
"10. push",
"11. pull",
"12. rock",
"13. balance",
"14. shake",
"15. float",
"16. duck",
"17. dodge",
"18. jab",
"19. poke",
"20. shove",
"21. carve",
"22. mold",
"23. freeze",
"24. wiggle",
"25. turn",
"26. fall",
"27. straighten",
"28. strike",
"29. chop",
"30. spin",
"31. kick",
"32. punch",
"33. hit",
"34. wring",
"35. shrug",
"36. hug",
"37. hang",
"38. sway",
"39. open",
"40. close",
"41. flap",
"42. burst",
"43. tap",
"44. grab",
"45. wrap",
"46. flick",
"47. pose"
};

String[] tMots4B = {
"nonprocedurally- locusts",
"movements",
"on",
"thematic",
"spoof",
"within",
"goings",
"anywhere",
"3. wavefront",
"2. ruben",
"6. singling",
"2. risers",
"9. melt",
"7. benchmark",
"6. glistened ",
"6. twill",
"9. swimming",
"99. pusan",
"22. pulp",
"91. rocker",
"01. balanced",
"20. shattered",
"32. floyd",
"22. duct",
"77. dodgers",
"89. jabbing",
"04. pokes",
"75. shortens",
"95. careen",
"25. molten",
"93. fretfulness",
"06. wigs",
"67. turnings",
"39. falstaff",
"72. strews",
"32. striptease",
"84. chou",
"21. spies",
"21. kickapoo",
"23. punished",
"84. hitlerite",
"29. wristwatch",
"48. shrill",
"45. huge",
"09. han",
"56. swansea",
"08. opened",
"04. clogs",
"01. flax",
"45. burbank",
"18. tapped",
"90. granny",
"20. wrapped",
"18. flicking",
"34. possessively"

};

String[] tMots4C = {
"noninterference- locations",
"movers",
"on",
"theatrical",
"spooling",
"withstanding",
"going",
"any",
"4. waving",
"2. rubbers",
"2. singapore",
"7. risings",
"6. mellow",
"9. benighted",
"4. glittered ",
"4. twinkled",
"0. swivel",
"60. pushdown",
"81. pulsations",
"28. rockefeller",
"11. baltimore",
"18. shatters",
"40. floors",
"64. duct",
"15. dodecahedra",
"67. jabs",
"46. poker",
"64. shorthand",
"88. caraway",
"53. molehill",
"30. freight",
"62. wightman",
"52. turnip",
"06. falsity",
"33. streaked",
"99. stretching",
"36. chopping",
"10. spinster",
"54. kicker",
"46. punctured",
"37. hitchcock",
"63. writings",
"75. shriek",
"92. hug",
"56. hands",
"41. swallowtail",
"78. operates",
"12. closure",
"15. flap",
"72. burners",
"89. tapes",
"23. grafting",
"59. wrangler",
"70. flirtation",
"22. postcondit"
};

String[] tMots4D = {
"nonmilitary- lockian",
"moves",
"on",
"thereupon",
"spouse",
"witnessing",
"goings",
"any",
"1. wavers",
"3. rubbers",
"6. singularities",
"5. risc",
"5. melisande",
"1. bends",
"6. glides ",
"1. twitched",
"3. swift",
"35. pushbutton",
"18. pulling",
"03. rockers",
"45. ballots",
"43. shaping",
"35. flower",
"74. duct",
"48. dodging",
"22. jab",
"13. poking",
"30. shouldering",
"69. carbolic",
"85. mold",
"30. frederico",
"90. wightman",
"05. turnable",
"27. falseness",
"94. strauss",
"31. stratify",
"62. cholera",
"25. spinner",
"24. kicked",
"04. puncture",
"77. hitlerian",
"67. writhe",
"78. shrew",
"23. hughes",
"60. hanna",
"17. swaps",
"32. operable",
"56. cloudier",
"05. flattering",
"59. burping",
"66. tappers",
"47. grasped",
"91. wrangled",
"76. flights",
"53. postulation"
};

String[] tMots5A = {
"from",
"slowest",
"to",
"quickest",
"1. Crawl",
"2. Plod",
"3. Trudge",
"4. Tiptoe",
"5. Creep",
"6. Edge",
"7. Worm",
"8. Stagger",
"9. Waddle",
"10. Traipse",
"11. Amble",
"12. Dawdle",
"13. Mosey",
"14. Saunter",
"15. Promenade",
"16. Slink",
"17. Maunder",
"18. Perambulate",
"19. Stroll",
"20. Walk",
"21. Scuttle",
"22. Strut",
"23. Sashay",
"24. Gad",
"25. Prance",
"26. Roll",
"27. Skip",
"28. Flounce",
"29. Stomp",
"30. Scoot",
"31. Scramble",
"32. Lope",
"33. Hie",
"34. Bound",
"35. Run",
"36. Hurry",
"37. Scamper",
"38. Spring",
"39. Rush",
"40. Gambol",
"41. Skitter",
"42. Dart",
"43. Race",
"44. Sprint",
"45. Streak",
"46. Gallop",
"47. Dash",
"48. Bolt",
"49. Barrel",
"50. Zoom",
"51. Zip"
};

String[] tMots5B = {
"frontal",
"sloped",
"to",
"quizzical",
"5. Crafty",
"9. Plower",
"1. Trues",
"3. Tipperary",
"2. Credulous",
"2. Edgewater",
"7. Work",
"7. Stalking",
"8. Wades",
"30. Translations",
"02. Ambivalence",
"33. Dawned",
"56. Moslemizes",
"30. Sausage",
"01. Probate",
"87. Slice",
"02. Mauritania",
"21. Persisting",
"38. Strawberry",
"53. Waldensian",
"91. Scuttle",
"94. Stravinsky",
"48. Saskatchewan",
"46. Gadget",
"05. Praiser",
"73. Role",
"59. Skip",
"80. Floodlit",
"26. Stocker",
"36. Scotland",
"64. Scrawling",
"36. Lopsided",
"92. Hierarchic",
"67. Bouncy",
"91. Rungs",
"59. Hurricane",
"67. Scary",
"13. Spruced",
"82. Rusts",
"71. Game",
"69. Skirt",
"50. Darwinize",
"13. Racket",
"78. Sprouting",
"96. Strategies",
"37. Gallstone",
"73. Dashing",
"52. Boltzmann",
"36. Barlow",
"87. Zoos",
"41. Kis"
};
String[] tMots5C = {
"frozen",
"slouch",
"to",
"quizzed",
"3. Crabapple",
"0. Plowman",
"1. Truncation",
"6. Tippers",
"5. Creamers",
"0. Edgerton",
"7. Worships",
"9. Stability",
"0. Wade",
"88. Translates",
"85. Ambushed",
"13. Dawning",
"88. Most",
"02. Saucepan",
"95. Pro",
"12. Slightly",
"01. Mauricio",
"92. Perseverance",
"77. Straightens",
"45. Walton",
"22. Sculptures",
"58. Stringing",
"59. Saskatoon",
"47. Gadgetry",
"16. Pray",
"53. Role",
"15. Skinning",
"18. Flowers",
"41. Stockpile",
"45. Scorings",
"71. Screeched",
"52. Lopsided",
"27. Hieronymus",
"24. Bought",
"74. Runtime",
"79. Hurwitz",
"15. Scans",
"75. Sprawling",
"62. Rusty",
"35. Gamma",
"74. Skirmishers",
"51. Darn",
"86. Racially",
"80. Sprain",
"41. Structurally",
"40. Gale",
"04. Dashed",
"81. Bologna",
"44. Barrages",
"80. Zoological",
"38. Yab"
};
String[] tMots5D = {
"frogs",
"slowness",
"to",
"quito",
"8. Crackling",
"0. Plotting",
"5. Truism",
"1. Tippecanoe",
"0. Creaming",
"2. Edgerton",
"6. Worn",
"1. Stalinist",
"1. Waded",
"09. Transmissions",
"39. Ambuscade",
"49. Dawned",
"02. Most",
"76. Saukville",
"19. Pronounced",
"23. Slicers",
"73. Mauritania",
"04. Perched",
"54. Strobed",
"86. Walnuts",
"41. Scuffled",
"02. Strangling",
"61. Saskatoon",
"48. Gadgetry",
"73. Practicality",
"77. Role",
"76. Skimps",
"36. Floating",
"14. Storks",
"91. Scorned",
"34. Screech",
"78. Lopez",
"43. Hierarchic",
"89. Boundaries",
"09. Runyon",
"88. Hurons",
"21. Scaled",
"89. Springfield",
"58. Rusher",
"06. Gamma",
"34. Skinned",
"43. Darwinistic",
"95. Racket",
"28. Sprouted",
"69. Strongheart",
"90. Galilee",
"70. Dashingly",
"23. Bolstered",
"23. Barnard",
"66. Zoom",
"91. Hoz"
};

String[] tMots6A = {
"performance",
"ideaz",
"two",
"three",
"stand",
"on",
"one",
"side",
"of",
"a",
"protruded",
"plank",
"another",
"moves",
"on",
"the",
"other",
"end",
"a",
"plank",
"x",
"placed",
"on",
"a",
"school",
"desk",
"the",
"PPL",
"school",
"desk",
"with",
"x",
"performers",
"placed",
"on",
"either",
"side",
"one",
"performer",
"edward",
"is",
"casting",
"arm",
"hand",
"lipstick",
"apply",
"to",
"plank",
"apply",
"to",
"another",
"person",
"then",
"they",
"apply",
"to",
"plank",
"kiss",
"plank",
"down",
"center",
"someone",
"cuts",
"the",
"entire",
"length",
"of",
"board",
"vas",
"aline",
"the",
"bottoms",
"of",
"yr",
"feet",
"try",
"to",
"dance",
"on",
"tarp",
"or",
"walk",
"down",
"plank",
"apply",
"lipstick",
"cutline",
"to",
"x",
"have",
"other",
"people",
"sit",
"on",
"one",
"stable",
"end",
"i",
"sit",
"on",
"the",
"other",
"and",
"cut",
"myself",
"off",
"repeat",
"x",
"ketchup",
"redpaint",
"in",
"mouth",
"write",
"word",
"on",
"wall",
"floor",
"spank",
"my",
"ass",
"pick",
"people",
"up",
"while",
"they",
"read",
"thingz",
"off",
"phone",
"or",
"receipt",
"paper",
"apply",
"paint",
"to",
"heelz",
"and",
"have",
"someone",
"drag",
"me",
"around",
"high",
"heelz",
"black",
"out",
"feet",
"with",
"magic",
"marker",
"black",
"trash",
"bags",
"latex",
"glovez",
"balloonz",
"filled",
"with",
"something",
"poetry",
"language",
"space",
"board",
"brick",
"stand",
"write",
"on",
"x",
"butler",
"nothing",
"lay",
"and",
"receive",
"projectionz",
"on",
"body",
"zizek",
"meaning",
"eater",
"blind",
"with",
"bags",
"over",
"our",
"heads",
"one",
"person",
"will",
"use",
"language",
"to",
"explain",
"their",
"movement",
"and",
"other",
"will",
"try",
"to",
"emulate",
"movement",
"tie",
"everyones",
"head",
"together",
"take",
"clothes",
"off",
"and",
"describe",
"them",
"x",
"mouthpiece",
"saw",
"x",
"into",
"mouth",
"shape",
"on",
"both",
"ends",
"x",
"x",
"people",
"carry",
"around",
"rd",
"person",
"reading",
"receipt",
"txt",
"have",
"someone",
"else",
"put",
"my",
"bootz",
"on",
"I",
"lick",
"them",
"p",
"jelly",
"feet",
"bag",
"head",
"have",
"some",
"yank",
"sheet",
"tarp",
"out",
"from",
"under",
"me",
"Carry",
"board",
"from",
"storage",
"shed"
};
String[] tMots6B = {
"persuading",
"ideal",
"twombly",
"threatens",
"staircases",
"on",
"onerous",
"side",
"of",
"a",
"propellers",
"placer",
"anon",
"moving",
"on",
"themselves",
"otherwise",
"endings",
"a",
"platonist",
"x",
"placed",
"on",
"a",
"schroeder",
"desmond",
"therapist",
"BMF",
"schaefer",
"destructions",
"witherspoon",
"x",
"perceptibly",
"playboy",
"on",
"either",
"sidestep",
"oneself",
"perfect",
"edwardine",
"is",
"cassites",
"armada",
"handful",
"lips",
"appoints",
"to",
"planoconvex",
"apprise",
"to",
"anomalous",
"peruse",
"theorist",
"theorization",
"appreciating",
"to",
"placement",
"kisses",
"platitude",
"downstairs",
"centigrade",
"someplace",
"cuttings",
"then",
"entropy",
"leniency",
"of",
"boa",
"vastness",
"alienating",
"theodosian",
"bottlers",
"of",
"yr",
"feelingly",
"try",
"to",
"dandelion",
"on",
"tardy",
"or",
"walnuts",
"downed",
"placidly",
"apprehension",
"lipton",
"cutters",
"to",
"x",
"havilland",
"others",
"peoples",
"sits",
"on",
"onerous",
"staley",
"endows",
"i",
"situation",
"on",
"theorizations",
"others",
"andes",
"cutthroat",
"mysteriousness",
"offhand",
"repents",
"x",
"ketchup",
"reducibility",
"in",
"mouton",
"wristwatches",
"workbook",
"on",
"walk",
"florin",
"spanking",
"my",
"assigners",
"picasso",
"peoria",
"up",
"whiteleaf",
"theodosian",
"realizably",
"thinner",
"officialdom",
"phone",
"or",
"recapitulated",
"papered",
"approved",
"paine",
"to",
"heeds",
"andes",
"having",
"somerville",
"drained",
"me",
"arousal",
"highest",
"heeds",
"blanks",
"outstripped",
"feelers",
"withholders",
"magnitude",
"marshal",
"blackout",
"trains",
"bagatelle",
"latinity",
"globally",
"balking",
"filaments",
"withholder",
"somnolent",
"poe",
"landmarks",
"spareness",
"boarding",
"brittany",
"starkly",
"writhe",
"on",
"x",
"buttercup",
"notables",
"laymen",
"andre",
"reclamations",
"probes",
"on",
"bodybuilding",
"xixec",
"meander",
"eats",
"blip",
"wit",
"bagel",
"overthrown",
"ours",
"headmaster",
"onerous",
"perpetrate",
"wily",
"used",
"lancer",
"to",
"expressive",
"thefts",
"moving",
"andalusian",
"others",
"wiley",
"trying",
"to",
"emulates",
"moves",
"tientsin",
"everlasting",
"heart",
"togo",
"takers",
"clone",
"officio",
"andrea",
"destined",
"thereof",
"x",
"mourner",
"sawmill",
"x",
"interlaces",
"mouse",
"shallowness",
"on",
"botany",
"endeared",
"x",
"x",
"peopled",
"carbonization",
"aromatic",
"rd",
"perspective",
"reacted",
"reconfigurations",
"vkb",
"have",
"some",
"elsie",
"putnam",
"my",
"bookcase",
"on",
"I",
"licentious",
"thereof",
"p",
"jelly",
"feels",
"bagging",
"heaved",
"haven",
"somali",
"yank",
"shea",
"tar",
"outdo",
"frostbite",
"underestimates",
"me",
"Carriers",
"boasted",
"frontal",
"stony",
"sheet"
};
String[] tMots6C = {
"perfection",
"identifications",
"twos",
"thrill",
"stare",
"on",
"oneida",
"sidesaddle",
"of",
"a",
"proud",
"placer",
"anomaly",
"movements",
"on",
"theology",
"otherworldly",
"endanger",
"a",
"planoconcave",
"x",
"plateaus",
"on",
"a",
"schematically",
"designator",
"theorist",
"VQY",
"schedulable",
"despise",
"withdrawals",
"x",
"percy",
"placards",
"on",
"either",
"sideboard",
"oneness",
"percy",
"edwards",
"is",
"cassius",
"armpits",
"hannibal",
"lipschitz",
"apprentices",
"to",
"plaguing",
"appearances",
"to",
"anonymous",
"perseid",
"theology",
"theirs",
"appian",
"to",
"playwright",
"kisser",
"plant",
"downtown",
"centrifugal",
"somatic",
"cutting",
"their",
"enters",
"lentil",
"of",
"boatloads",
"vassar",
"aliasing",
"thereafter",
"bothering",
"of",
"yr",
"feeder",
"trying",
"to",
"dangle",
"on",
"tardiness",
"or",
"waltham",
"downtowns",
"planes",
"appreciations",
"lipschitz",
"cutaneous",
"to",
"x",
"havana",
"othello",
"peopled",
"sit",
"on",
"oneida",
"stager",
"endeavored",
"i",
"sited",
"on",
"theology",
"otherwise",
"andrews",
"cute",
"mystic",
"officemate",
"replies",
"x",
"kettles",
"redden",
"in",
"mounts",
"wriggler",
"worthiness",
"on",
"walford",
"floored",
"spareness",
"my",
"assembly",
"picofarad",
"peopled",
"up",
"whiteleaf",
"theorizers",
"realists",
"thinner",
"officer",
"phosphor",
"or",
"receipt",
"paperweight",
"apportionment",
"pairings",
"to",
"heeded",
"andre",
"havoc",
"something",
"dragon",
"me",
"arousing",
"highfield",
"heeded",
"blanket",
"outermost",
"feel",
"witt",
"magnet",
"marketplace",
"blanchard",
"transferred",
"bagels",
"latter",
"gloom",
"ballpark",
"file",
"witchcraft",
"somatic",
"poetically",
"landscaping",
"sparest",
"boasted",
"bribers",
"stabilizer",
"writhed",
"on",
"x",
"butterers",
"notwithstanding",
"layering",
"andrei",
"recover",
"proliferating",
"on",
"bodice",
"xomiy",
"measuring",
"eat",
"blink",
"withdrew",
"bagley",
"oversight",
"ours",
"headland",
"onerous",
"persuasiveness",
"willingness",
"usenet",
"landings",
"to",
"experts",
"theatricals",
"moves",
"andorra",
"otherwise",
"willow",
"trying",
"to",
"emulator",
"moved",
"tiers",
"evenhanded",
"healthier",
"together",
"take",
"closets",
"offshore",
"anders",
"deserter",
"therewith",
"x",
"moulton",
"sawmill",
"x",
"interfacing",
"mourn",
"shall",
"on",
"botanical",
"endeavors",
"x",
"x",
"peony",
"carmela",
"aromatic",
"rd",
"persecuting",
"reacquired",
"reconsider",
"gfj",
"havilland",
"sommerfeld",
"elsevier",
"putter",
"my",
"boom",
"on",
"I",
"licensor",
"theatrical",
"p",
"jello",
"feeder",
"bagged",
"headphone",
"having",
"somali",
"yankee",
"sheds",
"tartuffe",
"outgrew",
"front",
"undergoing",
"me",
"Carrying",
"boarsh",
"frowned",
"stomacher",
"shell"
};
String[] tMots6D = {
"peruvian",
"identify",
"twofold",
"thrift",
"stabilizer",
"on",
"oneida",
"sidesaddle",
"of",
"a",
"protections",
"platinum",
"anodizes",
"movements",
"on",
"their",
"other",
"endure",
"a",
"playhouse",
"x",
"plainly",
"on",
"a",
"schoolrooms",
"despairing",
"themselves",
"VDN",
"schemers",
"desirably",
"withstands",
"x",
"persevere",
"placer",
"on",
"either",
"sidecar",
"one",
"persuades",
"edwards",
"is",
"cased",
"armco",
"hansel",
"lipton",
"appointee",
"to",
"players",
"applicative",
"to",
"anodizes",
"perpetrations",
"thefts",
"their",
"appender",
"to",
"planetary",
"kiss",
"playtime",
"downgrade",
"censored",
"sometime",
"cuttings",
"theology",
"entertainers",
"lengthwise",
"of",
"boastfully",
"vassal",
"alike",
"thermofax",
"botanist",
"of",
"yr",
"feels",
"try",
"to",
"dances",
"on",
"tardy",
"or",
"wales",
"downstream",
"playground",
"appalled",
"lippincott",
"cute",
"to",
"x",
"havana",
"otherwise",
"peopled",
"sit",
"on",
"ones",
"starred",
"endowment",
"i",
"site",
"on",
"therapies",
"othello",
"andromache",
"cutover",
"mystical",
"offended",
"repudiates",
"x",
"kettles",
"reduce",
"in",
"mountaineers",
"writing",
"words",
"on",
"wallets",
"flocked",
"spanishize",
"my",
"assurer",
"pickman",
"peony",
"up",
"whirls",
"theorist",
"reassignments",
"thief",
"officially",
"phoenicia",
"or",
"recombined",
"paper",
"approves",
"pail",
"to",
"heedlessly",
"andre",
"havana",
"somerset",
"draftee",
"me",
"aroused",
"highnesses",
"heeling",
"blazes",
"outright",
"feedings",
"withal",
"magnolia",
"martyrdom",
"blasters",
"tramp",
"bagger",
"latrine",
"glories",
"ballast",
"filament",
"wither",
"someday",
"poets",
"landscaping",
"spaceship",
"boats",
"brittle",
"startled",
"writer",
"on",
"x",
"but",
"nothing",
"layout",
"andean",
"recorded",
"probabilities",
"on",
"bodily",
"jeher",
"measurable",
"eats",
"blindfolded",
"withheld",
"bagpipe",
"overhanging",
"our",
"hearken",
"oneself",
"perishers",
"willy",
"use",
"landwehr",
"to",
"expedition",
"therapists",
"movings",
"andre",
"other",
"wilting",
"trying",
"to",
"emulation",
"movers",
"tie",
"everybody",
"hearings",
"togetherness",
"takings",
"clothe",
"officiously",
"andrew",
"desiring",
"thermodynamics",
"x",
"mounts",
"sawed",
"x",
"interchangings",
"mounds",
"shamefully",
"on",
"bottled",
"endings",
"x",
"x",
"peoria",
"cars",
"arouses",
"rd",
"persecutor",
"reacher",
"recursed",
"qrr",
"having",
"some",
"elsevier",
"putt",
"my",
"bookcase",
"on",
"I",
"lice",
"therein",
"p",
"jellies",
"feeney",
"bagpipes",
"heaviness",
"haves",
"somalia",
"yankton",
"shears",
"target",
"outrage",
"frontier",
"underplayed",
"me",
"Carnivorous",
"boatswain",
"frozen",
"storeys",
"shells"
};



String[] tMots7A = {
"of",
"a",
"situation",
"or",
"condition",
"extremely",
"bad",
"unpleasant",
"and",
"degrading",
"abject",
"poverty",
"synonyms",
"wretched",
"miserable",
"hopeless",
"pathetic",
"pitiful",
"pitiable",
"piteous",
"sorry",
"woeful",
"lamentable",
"degrading",
"appalling",
"atrocious",
"awful",
"abject",
"poverty",
"of",
"an",
"unhappy",
"state",
"of",
"mind",
"experienced",
"to",
"the",
"maximum",
"degree",
"his",
"letter",
"plunged",
"her",
"into",
"abject",
"misery",
"of",
"a",
"person",
"or",
"their",
"behavior",
"completely",
"without",
"pride",
"or",
"dignity",
"self",
"abasing",
"an",
"abject",
"apology",
"synonyms",
"contemptible",
"base",
"low",
"vile",
"worthless",
"debased",
"degraded",
"despicable",
"ignominious",
"mean",
"unworthy",
"ignoble",
"an",
"abject",
"sinner",
"obsequious",
"groveling",
"fawning",
"toadyish",
"servile",
"cringing",
"sycophantic",
"submissive",
"craven",
"an",
"abject",
"apology"
};
String[] tMots7B = {
"of",
"a",
"sitting",
"or",
"constituencies",
"extremal",
"badge",
"unpaid",
"andalusia",
"degenerated",
"abjured",
"poverty",
"synergy",
"wretched",
"misting",
"hopper",
"patterning",
"pityingly",
"pithiness",
"pities",
"sordidly",
"woefully",
"lame",
"degree",
"appellation",
"atrophying",
"awful",
"abject",
"poverty",
"of",
"an",
"unhappy",
"stalk",
"of",
"minsk",
"exposition",
"to",
"thelma",
"maximally",
"degenerated",
"histogram",
"letitia",
"plunderer",
"herein",
"intentions",
"abject",
"mishaps",
"of",
"a",
"perpetuated",
"or",
"theory",
"beholds",
"complementary",
"withholders",
"privately",
"or",
"digitizing",
"selwyn",
"abandoning",
"an",
"abjures",
"apostate",
"syndrome",
"contradistinction",
"baseboards",
"lowliest",
"vilified",
"workload",
"debby",
"degenerative",
"deserter",
"ignores",
"measured",
"unwinding",
"ignominious",
"an",
"abjections",
"singapore",
"observance",
"groups",
"fawn",
"toasted",
"serializations",
"crimean",
"sycophant",
"subsisting",
"crater",
"an",
"abjections",
"apologists"
};
String[] tMots7C = {
"of",
"a",
"site",
"or",
"congressionally",
"extramarital",
"badgers",
"unprofitable",
"andrew",
"degenerative",
"abjures",
"poverty",
"synchrotron",
"wrenches",
"misconceptions",
"hopeful",
"patchwork",
"pitfall",
"pitiers",
"pitched",
"sort",
"woeful",
"laminar",
"degeneracy",
"applaud",
"atrocious",
"awful",
"abjuring",
"poverty",
"of",
"an",
"unhappiness",
"stalled",
"of",
"minimum",
"exploration",
"to",
"thence",
"maxwell",
"degradation",
"histogram",
"lettering",
"plurals",
"herring",
"intersection",
"abjectness",
"misuse",
"of",
"a",
"personalities",
"or",
"theories",
"behaviorally",
"comparable",
"witness",
"princely",
"or",
"digressing",
"selecting",
"abandoning",
"an",
"abjectness",
"apotheoses",
"synthesized",
"conceits",
"bassett",
"lowest",
"vileness",
"worm",
"debates",
"degenerating",
"descriptors",
"ignominious",
"measurement",
"unwrap",
"ignoble",
"an",
"abjuring",
"sincere",
"observers",
"grossman",
"fawns",
"toaster",
"servicing",
"critical",
"sycophantic",
"subtlest",
"cradles",
"an",
"abjure",
"apocalypse"
};
String[] tMots7D = {
"of",
"a",
"sits",
"or",
"conrad",
"external",
"badly",
"unprescribed",
"andes",
"degenerated",
"abjure",
"poverty",
"synchrony",
"wreck",
"miss",
"hopelessly",
"patronized",
"pits",
"pitney",
"pitch",
"sorcerer",
"woe",
"lames",
"degrading",
"appraisals",
"atrophy",
"awful",
"abjectness",
"poverty",
"of",
"an",
"unheeded",
"stairways",
"of",
"mini",
"expound",
"to",
"theodore",
"maxine",
"degenerates",
"historic",
"letterhead",
"plunder",
"heralded",
"interrogations",
"abjuring",
"misunderstand",
"of",
"a",
"perspiration",
"or",
"thermometers",
"behalf",
"commonest",
"witch",
"priscilla",
"or",
"digitalis",
"select",
"abased",
"an",
"abjections",
"apologizing",
"synthesized",
"confessor",
"basses",
"lowers",
"villainously",
"workshop",
"debaters",
"degrade",
"deservingly",
"ignorant",
"measured",
"unwittingly",
"ignorant",
"an",
"abjured",
"singleness",
"obsessive",
"grossman",
"fawn",
"toaster",
"serbian",
"crisis",
"sycophant",
"subsequence",
"crackling",
"an",
"abjuring",
"apotheosis"
};

String[] tMots8A = {
"centimeter",
"long",
"lengths",
"of",
"copper",
"wire",
"copper",
"space",
"islands",
"copper",
"wires",
"to",
"wrap",
"the",
"world",
"the",
"pre",
"dated",
"makeshift",
"decisions",
"a",
"big",
"house",
"banging",
"on",
"a",
"drum",
"for",
"survival",
"for",
"fitness",
"for",
"dexterity",
"cooperatively",
"bang",
"together",
"and",
"own",
"the",
"house",
"ya",
"banging",
"and",
"ya",
"cooperation",
"ya",
"dexterity",
"and",
"ya",
"cooperation",
"glitchy",
"little",
"innards",
"makeshift",
"lantern",
"makeshift",
"candle",
"made",
"out",
"of",
"my",
"duplicated",
"head",
"carved",
"out",
"the",
"temple",
"of",
"the",
"dupe",
"filled",
"the",
"hole",
"in",
"the",
"dupe",
"with",
"beeswax",
"dollar",
"bill",
"wic",
"women",
"infants",
"children",
"put",
"on",
"the",
"government",
"s",
"grave",
"doing",
"what",
"s",
"safe",
"and",
"removing",
"clothes",
"probably",
"a",
"thief",
"probably",
"a",
"victim",
"probably",
"too",
"resentful",
"probably",
"too",
"stressful",
"failure",
"and",
"success",
"are",
"not",
"spectrums",
"saturated",
"stress",
"but",
"you",
"ain",
"t",
"gotta",
"worry",
"about",
"me",
"ya",
"got",
"yr",
"own",
"yeah",
"the",
"coveted",
"formation",
"of",
"crystals",
"in",
"dark",
"caves",
"cause",
"suffering",
"why",
"my",
"opportunity",
"is",
"displaced",
"oppression",
"why",
"guess",
"imma",
"keep",
"drinking",
"this",
"water"
};
String[] tMots8B = {
"censor",
"loneliness",
"lenore",
"of",
"copy",
"wiry",
"copier",
"spaniardizations",
"islandia",
"copywriter",
"wiretap",
"to",
"wrapped",
"theorist",
"workbench",
"thessaly",
"prevails",
"date",
"makeup",
"decibel",
"a",
"bight",
"household",
"bandages",
"on",
"a",
"drunkard",
"fortiori",
"surmised",
"forgiving",
"fittingly",
"forenoon",
"dexedrine",
"cookery",
"banned",
"toggling",
"anding",
"owned",
"thea",
"housebroken",
"ya",
"bandaging",
"andrei",
"ya",
"cools",
"ya",
"dexedrine",
"anderson",
"ya",
"cooperate",
"glimmering",
"littering",
"innovate",
"makers",
"langeland",
"makeshift",
"candler",
"maddox",
"outwit",
"of",
"my",
"duplex",
"hearers",
"carcinogenic",
"outlet",
"thermostat",
"templates",
"of",
"thereupon",
"duplicates",
"filmed",
"thereon",
"hole",
"in",
"thereby",
"duponts",
"witnesses",
"beecham",
"doled",
"billeting",
"wicks",
"woman",
"inflict",
"chirped",
"putting",
"on",
"theorists",
"governess",
"s",
"gratified",
"doings",
"whack",
"s",
"safely",
"andorra",
"remonstrated",
"clotho",
"propounded",
"a",
"thinker",
"proselytized",
"a",
"victimize",
"promising",
"tool",
"resetting",
"proteins",
"toothbrush",
"straight",
"fairyland",
"andromeda",
"sucking",
"ares",
"notary",
"spencer",
"satchel",
"stringer",
"butterfly",
"your",
"ainu",
"t",
"gotos",
"workspace",
"aboriginal",
"me",
"ya",
"gothicizing",
"yr",
"owning",
"yeasts",
"theoretic",
"covenant",
"formality",
"of",
"crystal",
"in",
"dared",
"caveman",
"cauldron",
"sufferance",
"why",
"my",
"oppress",
"is",
"dislodge",
"oppositeness",
"why",
"guelph",
"immigrates",
"keeled",
"drily",
"thief",
"waters"
};
String[] tMots8C = {
"centralized",
"loner",
"lens",
"of",
"copiousness",
"wiriness",
"copernicus",
"sparks",
"island",
"copes",
"wire",
"to",
"wrapped",
"theorizer",
"worldwide",
"therapists",
"predictable",
"dating",
"makes",
"decelerate",
"a",
"biggest",
"householder",
"bananas",
"on",
"a",
"drunks",
"formulate",
"surveyed",
"forearms",
"fitfully",
"forestalls",
"dexterity",
"coordinations",
"bandwidths",
"toggle",
"andalusian",
"ownership",
"theodore",
"house",
"ya",
"banging",
"anding",
"ya",
"cooperation",
"ya",
"dexedrine",
"andrew",
"ya",
"coolers",
"gliders",
"lithography",
"innuendo",
"makers",
"langeland",
"makers",
"candies",
"mad",
"outweighing",
"of",
"my",
"duplicators",
"heaviness",
"cares",
"outruns",
"thermosphere",
"temperament",
"of",
"theorizer",
"duponts",
"fillable",
"thermostat",
"hollowing",
"in",
"thea",
"duplicator",
"witnesses",
"beefed",
"doled",
"bills",
"wicker",
"woman",
"infringements",
"chimes",
"putty",
"on",
"therapies",
"governmentally",
"s",
"granulates",
"doings",
"whaling",
"s",
"safeguarding",
"andalusia",
"remembered",
"closures",
"promoted",
"a",
"thinker",
"prokofieff",
"a",
"viciousness",
"proclaimers",
"toothpick",
"restrictive",
"protector",
"toolers",
"straightforwardness",
"fain",
"andover",
"succumb",
"arena",
"notably",
"specializing",
"sating",
"straightened",
"buttock",
"youngly",
"ainus",
"t",
"gotten",
"worry",
"aboveboard",
"me",
"ya",
"goto",
"yr",
"owns",
"yeasts",
"therapeutic",
"covent",
"forger",
"of",
"cryptographer",
"in",
"darkly",
"cavalier",
"caucasus",
"sufficient",
"why",
"my",
"opposed",
"is",
"discretely",
"oppression",
"why",
"guests",
"immemorial",
"keener",
"drivers",
"thinks",
"waterings"
};
String[] tMots8D = {
"centripetal",
"loners",
"lengthwise",
"of",
"copious",
"wiring",
"copious",
"spatial",
"isle",
"copes",
"wiring",
"to",
"wrappings",
"therapies",
"worth",
"thematic",
"precise",
"dates",
"make",
"decorating",
"a",
"bight",
"housing",
"banishing",
"on",
"a",
"drury",
"forestall",
"survivors",
"fortify",
"fitting",
"formed",
"dexterity",
"cooped",
"bantered",
"togetherness",
"andre",
"owned",
"theorist",
"housetops",
"ya",
"bandit",
"andes",
"ya",
"coordination",
"ya",
"dexedrine",
"andorra",
"ya",
"cookery",
"glimmers",
"lithograph",
"innate",
"makable",
"lance",
"making",
"canning",
"madeline",
"outlived",
"of",
"my",
"dupe",
"healthful",
"caribou",
"outvotes",
"theatricals",
"temperateness",
"of",
"thenceforth",
"duplicated",
"filipino",
"thermodynamic",
"holes",
"in",
"there",
"duplicity",
"witherspoon",
"beers",
"dolphin",
"bill",
"wicked",
"women",
"infallible",
"chillier",
"puttering",
"on",
"they",
"governance",
"s",
"granny",
"doing",
"whatever",
"s",
"safeguarding",
"andrew",
"remote",
"clog",
"prospectives",
"a",
"thief",
"proclaim",
"a",
"victual",
"promoter",
"toothbrush",
"resolving",
"professes",
"toomey",
"struggles",
"faints",
"andy",
"successes",
"areas",
"notational",
"spear",
"sate",
"strangers",
"buttoned",
"youth",
"ainu",
"t",
"gothicizing",
"wordy",
"abominable",
"me",
"ya",
"gothicizes",
"yr",
"owned",
"yeasts",
"thereafter",
"covent",
"forlornly",
"of",
"cryptographically",
"in",
"darning",
"cavity",
"causeways",
"sufficiently",
"why",
"my",
"oppressor",
"is",
"dislocations",
"opposable",
"why",
"guest",
"immense",
"keen",
"driest",
"thieves",
"waterfalls"
};
